### ISSUE TITLE
Slow run time

### ISSUE THREAD

**Issue by ghost** [rackspace/php-opencloud#122]
Hi,

I've updated to the latest release (RAXSDK_VERSION 1.5.7), from RAXSDK_VERSION v1.5.4 and the speed is extremely slow, and seems to just hang for a few seconds when attempting to load a single object from ObjectStore. I've reverted back to the old build and things run fine again.

**Comment by bacheson** [comment]
This issue is alive and well in 2015. I'm seeing 10-15 minute upload times over the internal network for a 10mb file using bulk extract.

**Comment by jamiehannaford** [comment]
@bacheson Can you [enable HTTP wire logging](http://docs.php-opencloud.com/en/latest/debugging.html#strategy-2-wire-logging) and send the output to jamie.hannaford@rackspace.com, please? If you could also send a snippet of the PHP code you're using, that would be great.
