### ISSUE TITLE
Appending data to an existing DataObject

### ISSUE THREAD

**Issue by stephenbunch** [rackspace/php-opencloud#178]
I see [examples](https://github.com/rackspace/php-opencloud/blob/master/docs/quickref.md#create-a-new-object-in-a-container) showing how to create new DataObjects. Is it possible to append data to an existing object? I want to push chunks directly to Cloud Files as I get them instead of composing the file on the server and doing a single (massive) push once the upload has finished.

This is basically what I'm trying to accomplish:
1. User clicks to upload 600 mb QuickBooks file.
2. File uploads to the server in chunks via ajax.
3. Server sends chunks to Cloud Files on each request.
4. User sees progress bar move as each chunked upload request completes.

I see there's a [spec](http://docs.rackspace.com/files/api/v1/cf-devguide/content/Chunked_Transfer_Encoding-d1e2092.html) for chunked uploads.

**Comment by AtmanCore** [comment]
@stephenbunch do you have code that write to database or where you listening to event? 

Thanks,
