### ISSUE TITLE
Suggestion: Ability to pass a progress handler to OpenCloud\ObjectStore\Resource\AbstractContainer->uploadObject()

### ISSUE THREAD

**Issue by flcoder** [rackspace/php-opencloud#301]
It would be total badassery to easily specify a progress monitoring handler to this function.

Configuring guzzle's $options is daunting to me still after much reading, but uploadObject doesn't provide an $options parameter, even if I knew what I was doing with the parameter in the first place in order to 'turn on' progress events.

I was able to accomplish monitoring via setupObjectTransfer instead and passing 'progress'=>TRUE as an array member along with $name and ($path or $body).  And perhaps this is the intended method to use when you want progress monitoring.

With $client as reference to a Rackspace object:

``` php
$client->getEventDispatcher()->addListener(
    'curl.callback.progress',
    function(Guzzle\Common\Event $event) {

        // determine upload_size
        $event['upload_size'];  // for some reason I could not simply
                                // $event->upload_size, not sure why.

        // determine uploaded
        $event['uploaded'];
    }

);
```

...then, $transfer = $container->setupObjectTransfer($opts), and then $transfer->upload()

One side effect when turning on progress monitoring, is that there is unwanted output, the origins of which I am unsure about.  In order to avoid this output, I've used ob_start() before calling $transfer->upload() and ob_end_clean() after.  If this behavior could somehow be changed, that would be swell, but I believe it may be what curl does on its own, not guzzle or php-opencloud.

This solution is pretty OK for my purposes, but this adds a listener to the Client when I really only want to add a handler to the specific Request.  I might want to do another request with a different handler, and I suppose there may be all kinds of ways to accomplish this, but just supplying a closure as a handler to the uploadObject function would be super friendly.

**Comment by AtmanCore** [comment]
I have to print the progress in Javascript function. I am new to getEventDispatcher. Can anybody tell me how can I show progress in JS after uploadObject called ?

Thanks,
