### ISSUE TITLE
Server metadata and extra request

### ISSUE THREAD

**Issue by notFloran** [rackspace/php-opencloud#500]
Hi,

I have a question about the metadata of Server. 

The response of the openstack/rackspace api for */servers* include metadata. (see https://github.com/rackspace/php-opencloud/blob/working/tests/OpenCloud/Tests/Compute/_response/Server_List.resp) but when I get a list of servers from the Compute service with the SDK, automatically a request is made for each server to retrieve the metadata. 

Why not retrieve metadata from the servers response ?

**Comment by notFloran** [comment]
The problem is that Server metadata have their own class and I have:
* **OpenCloud\Common\Metadata** in *$info->metadata* or *$this->metadata*
* **OpenCloud\Compute\Resource\ServerMetadata** when loaded from *$this->metadata()*

I have a question about *ServerMetadata* : why *Server* has his own metadata class while *Image* and *Server* seems to have the same way to handle metadata.

**Comment by jamiehannaford** [comment]
@notFloran I'm not sure why it was originally created, but my guess is that it differed significantly from some of the earliest services we supported (like Swift). Since it was added, we couldn't really revoke the class without releasing a new major version - so we're stuck with it until v2.
