### ISSUE TITLE
SSL Read Error when uploading to Rackspace CloudFiles

### ISSUE THREAD

**Issue by mrpdean** [rackspace/php-opencloud#501]
Hi,

I've run into a strange error when I try to upload numerous images (as part of a data import process) to Rackspace CloudFiles.

[Guzzle\Http\Exception\CurlException]
  [curl] 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 [url] https://storage101.syd2.clouddrive.com/v1/MossoCloudFS_8c3cef2b-4915-4d8e
  -8c39-4633425e3bee/vc-sandbox/atdw/0001/01/thumb_86_atdw_small.jpeg

When I ran the process from my local PC it worked (though it was slow) however when I run the same process on our Rackspace Cloud server I get that error.

The error appears about a quarter of the way through the process so I was thinking it might be some sort of rate limit, however the exception message doesn't really provide any hints to that affect.

Any help would be most appreciated.

Thanks

**Comment by mrpdean** [comment]
Hmm ok, I will try setting up a new cloud server and see if that works.

If that doesn't work I think I'm going to have to move over to AWS and see
if their network is any more reliable as this is becoming quite a problem
for me.

Thanks.

**Comment by jamiehannaford** [comment]
@mrpdean Unfortunately I don't think there's a silver bullet to an issue like this. There are various things you can do to suppress or mitigate the SSL errors, but each has its own drawbacks:

1. Disable SSL verification like this:

```php
'curl.options' => array(
   CURLOPT_SSL_VERIFYHOST => false, 
   CURLOPT_SSL_VERIFYPEER, false
)
```

I recommend against doing this, though - because it undermines the effectiveness of secure transport, which is the entire point of HTTPS. However if you're desperate and trust the source, it might be a suitable workaround.

You might also want to experiment with the `ssl.certificate_authority` option as documented [here](https://github.com/guzzle/guzzle3/blob/master/docs/http-client/client.rst#configuration-options).

2. Upgrade your cURL install. You mention you're running v7.35, but the latest version is v7.39. I read somewhere recently that a few bugs were introduced into recent Ubuntu images with cURL, so upgrading might help.

3. Implement a retry policy, which resends connections that have resulted in a particular error. For example, you can tell Guzzle (the underlying HTTP library) to retry connections that have resulted in a particular HTTP status (403 Forbidden, etc.) or a particular cURL error code (56 SSL read in your case). To do this, use the code here: https://gist.github.com/jamiehannaford/8432889

**Comment by ycombinator** [comment]
Hi @mrpdean, could you tell us what flavor of Rackspace Cloud Server you are using? Thank you.

**Comment by mrpdean** [comment]
Hi,

The server flavor is:  8 GB General Purpose v1

I'll try some of the suggestions from your previous post tonight and see
how that goes.

I don't really need https as there is nothing sensitive about the data I'm
trying to upload to CloudFiles so hopefully disabling SSL verification will
work.

It's just frustrating because the whole process works fine from my Dev PC
-> CloudFiles  but not from my RS Server -> CloudFiles.

Anyway, I appreciate all the assistance you've given me, especially as the
problem doesn't seem to be with php-opencloud.

I'll let you know how I go with your previous suggestions.

Thanks.

**Comment by mrpdean** [comment]
Quick update:

Disabling SSL verification didn't help.

I tried to update CURL to version 7.39 but only  curl --version reports 7.39.   php -i | grep 'cURL Information' still reports version 7.35 so I must have missed something.  Linux isn't my strong point so I might have to get my tech to look into that.

**Comment by ycombinator** [comment]
Thanks @mrpdean. Would you be able to tell us your server's ID as well? In the Rackspace Cloud Control Panel, the ID is shown on a specific server's details page (see screenshot below):

![screen shot 2015-01-03 at 4 32 46 am](https://cloud.githubusercontent.com/assets/51061/5602431/b55f6cfe-9301-11e4-92bd-2c56e3da372c.png)

**Comment by mrpdean** [comment]
Sure. The server id is:
 
2bed2276-2826-4d9a-9420-ae2cd8f33b73

Thanks

**Comment by ycombinator** [comment]
Thanks, I've passed along your server flavor and ID to our Cloud Servers team so they can determine if there's anything going on with that particular flavor of Cloud Servers or your specific Cloud Server in SYD.

**Comment by mrpdean** [comment]
Thanks.

**Comment by ycombinator** [comment]
Hi @mrpdean,

Were you able to try the same code from another server in the SYD region? If not, would you mind trying that from a *Standard* flavor server? The Cloud Servers team thinks this issue might be specific to Performance flavor servers and are trying to narrow it down further so they can diagnose and fix.

Thanks,

Shaunak

**Comment by mrpdean** [comment]
Hi @ycombinator,

I did as you suggested and created a 4GB Standard Instance and ran the process on that server and although significantly slower due to the lower server specs, the process did indeed complete successfully each time I ran it :)

So the issue does seem to be specific to the performance flavour of servers.  I hope the Cloud Server team will be able to fix it on the performance flavors as I prefer to run the performance flavors in my production environment.

Thanks,

**Comment by ycombinator** [comment]
Hi @mrpdean,

Our Cloud Servers team has one more question: are you running your code only on the Cloud Sever with  ID = 2bed2276-2826-4d9a-9420-ae2cd8f33b73 (before you spun up the Standard Instance) or have you spun up multiple Performance Cloud Servers to run your code? The team would like to test a fix and want to make sure all your Performance Cloud Servers get it.

Thanks,

Shaunak

**Comment by mrpdean** [comment]
Hi @ycombinator 

At the moment it's only that one performance server running the code.  Eventually (when the site goes live) I will spin up a second server however at the moment it's just the one.

Thanks.

**Comment by ycombinator** [comment]
Hi @mrpdean,

Thanks. The Cloud Servers team has made some fixes to the physical machine on which your Performance Cloud Server is running. Would you mind re-running your code on it to check if their change resolved the issues you were seeing?

Thanks,

Shaunak

**Comment by mrpdean** [comment]
Hi @ycombinator,

Yay!!!   The process now runs flawlessly on my performance flavored server.  Thank you so much for all your assistance in getting this resolved.  Now my only question is, if I spin up a second server will the Cloud Server team need to perform some wizardry on that machine as well, or should it just work for new performance servers from now on?

Thanks.

**Comment by ycombinator** [comment]
Hi @mrpdean,

Thanks for confirming the fix on your performance Cloud Server instance.

The Cloud Servers team is now applying the same fix across all performance servers in SYD. They expect to be done by Saturday morning Sydney time. I will post an update here as soon as they are done.

After that you should be able to spin up a second performance Cloud Server without requiring any special magic dust. It should Just Work™ as it normally would.

Shaunak

**Comment by ycombinator** [comment]
Hi @mrpdean,

The Cloud Servers team has completed their work across all performance servers in SYD. You should be able to spin up another performance Cloud Server and your code should work without the SSL issues.

Thank you for your patience with this,

Shaunak

**Comment by mrpdean** [comment]
Thanks @ycombinator.  That's great news.

**Comment by ycombinator** [comment]
Hi @mrpdean, I'm closing out this issue as I think it has been resolved. Please open a new one if necessary. Thanks, Shaunak
