### ISSUE TITLE
Do not use own Logger's Deprecated call

### ISSUE THREAD

**Issue by Rvanlaak** [rackspace/php-opencloud#511]
We are injecting the Symfony [`Monolog`](https://github.com/Seldaek/monolog) Logger to replace the Logger from the library. This does result in errors when the `ObjectStore` is trying to call `Logger::deprecated()` in the `bulkDelete` action, because it is not in the [PSR-3 Logger interface](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md)

Please use `Logger::warning()` everywhere, so other Loggers can be injected properly. We will make a PR for the `Logger` occurences in the `ObjectStore` part.

**Comment by ycombinator** [comment]
Fixed via #512. See https://github.com/rackspace/php-opencloud/pull/512#issuecomment-69012112 for details.
