### ISSUE TITLE
Cannot specify security groups when creating server

### ISSUE THREAD

**Issue by slashterix** [rackspace/php-opencloud#516]
OpenCloud\Compute\Resource\Server->create() does not support security groups, and there appears to be no way to add them after the server is created either.

**Comment by jamiehannaford** [comment]
We do not currently support this OpenStack extension, but it's something we can add to the roadmap

**Comment by slashterix** [comment]
Yes please!

**Comment by fifieldt** [comment]
This is pretty critical :) What are the latest plans?

**Comment by fifieldt** [comment]
Sorry, some context - I'm trying to add support for php-opencloud to the "Writing your First OpenStack Application" tutorial, but can't due to this missing functionality. This is not really an extension so much as implemented in basically every cloud :)

**Comment by fifieldt** [comment]
Thanks!
