### ISSUE TITLE
Add listing CDN containers to Object Store user guide

### ISSUE THREAD

**Issue by ycombinator** [rackspace/php-opencloud#528]
This should include:
* [ ] One or more sections in https://github.com/rackspace/php-opencloud/blob/master/docs/userguide/ObjectStore/USERGUIDE.md
* [ ] Corresponding code samples in https://github.com/rackspace/php-opencloud/tree/working/samples/ObjectStore

See https://github.com/jamiehannaford/php-opencloud/commit/a9f8bdd3b265b7928992acd26f95369512f78357 for reference.

**Comment by jamiehannaford** [comment]
This has [documentation](http://docs.php-opencloud.com/en/latest/services/object-store/cdn.html#list-cdn-enabled-containers) now, so closing
