### ISSUE TITLE
php composer.phar require rackspace/php-opencloud doesn't work

### ISSUE THREAD

**Issue by johnerck** [rackspace/php-opencloud#529]
php composer.phar require rackspace/php-opencloud doesn't work.

![fail](https://cloud.githubusercontent.com/assets/1895438/5846167/841eea74-a176-11e4-95e0-75724f75eb44.png)

**Comment by ycombinator** [comment]
Do you have a `composer.json` file in the folder from where you are running `php composer.phar require rackspace/php-opencloud `? If so, could you paste its contents here, please? Thanks.

**Comment by johnerck** [comment]
{
    "require":
    {
        "rackspace/php-opencloud": "dev-master",
        "phpclasses/oauth-api": ">=1.0.39"
    },
    "repositories":
    [
		{
			"type": "composer",
			"url": "http:\/\/www.phpclasses.org\/"
		},
		{
			"packagist": false
		}
	]
}

**Comment by johnerck** [comment]
php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package rackspace/php-opencloud could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by johnerck** [comment]
I'm running these command from my project's root directory, right next to my project's .git dir

**Comment by ycombinator** [comment]
Thanks. Let me try to reproduce and get back to you.

**Comment by ycombinator** [comment]
Try removing this section:

```
    {
       "packagist": false
    }
```

It is preventing Composer from downloading any packages from [Packagist](https://packagist.org/), which is where we publish php-opencloud.

**Comment by johnerck** [comment]
Awesome. That did the trick. Thanks.

**Comment by johnerck** [comment]
My composer.json file did get cloned down. It does not include the '"packagist": false' line as I removed that, added, then committed, prior to git cloning the project to my new machine. On my new machine, after the project clone, it looks like:

{
    "require":
    {
        "rackspace/php-opencloud": "dev-master",
        "phpclasses/oauth-api": ">=1.0.39"
    },
    "repositories":
    [
		{
			"type": "composer",
			"url": "http:\/\/www.phpclasses.org\/"
		}
	]
}

**Comment by johnerck** [comment]
When I run 'php composer.phar update' I get the following:

php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
