### ISSUE TITLE
"php composer.phar update" not pulling in project files for php-opencloud

### ISSUE THREAD

**Issue by johnerck** [rackspace/php-opencloud#530]
I start by "git clone"ing my project to a new machine. All the files I need get cloned down to my machine except for vendor/rackspace/php-opencloud. That directory is empty and therefore breaks my web app when I try to run it locally on my new machine.

Since composer.json and composer.phar did get cloned down fine, I figured running "php composer.phar update" would download the library files, but no.

What am I missing?

How am I to get the rackspace/php-opencloud files onto my computer after cloning the project they are supposed to already be a part of?

**Comment by ycombinator** [comment]
> Since composer.json and composer.phar did get cloned down fine, I figured running "php composer.phar update" would download the library files, but no.

A couple of things:

1. What does the `composer.json` that gets cloned down look like? Does it include the `"packagis"t: false` line?

2. What happens when you run `php composer.phar update`? What message(s) do you see?

**Comment by ycombinator** [comment]
I see your comments at https://github.com/rackspace/php-opencloud/issues/529#issuecomment-70938690 and https://github.com/rackspace/php-opencloud/issues/529#issuecomment-70938944. Lets continue the conversation in this issue to keep it all in one place and as the other one is already closed.

After cloning, what is in your `vendor` folder? What does `ls -l vendor` show?

**Comment by johnerck** [comment]
Sorry! Just realized I replied on the wrong thread! Fixing now...

**Comment by johnerck** [comment]
My composer.json file did get cloned down. It does not include the '"packagist": false' line as I removed that, added, then committed, prior to git cloning the project to my new machine. On my new machine, after the project clone, it looks like:

{
"require":
{
"rackspace/php-opencloud": "dev-master",
"phpclasses/oauth-api": ">=1.0.39"
},
"repositories":
[
{
"type": "composer",
"url": "http:\/\/www.phpclasses.org\/"
}
]
}

**Comment by johnerck** [comment]
When I run 'php composer.phar update' I get the following:

php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

**Comment by ycombinator** [comment]
Thanks for fixing the thread.

After cloning, what is in your `vendor` folder? What does `ls -l vendor` show?

**Comment by johnerck** [comment]
After running the update on my clean, just cloned repo, I get:

 git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   vendor/autoload.php
#	modified:   vendor/composer/autoload_real.php
#
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by johnerck** [comment]
ls -al vendor/
total 24
drwxr-xr-x  10 johnerck  501   340 Jan 21 14:55 .
drwxr-xr-x  16 johnerck  501   544 Jan 21 14:28 ..
-rw-r--r--@  1 johnerck  501  6148 Jan 21 14:28 .DS_Store
-rw-r--r--   1 johnerck  501   183 Jan 21 14:55 autoload.php
drwxr-xr-x   8 johnerck  501   272 Jan 21 14:55 composer
drwxr-xr-x   6 johnerck  501   204 Jan 21 13:45 guzzle
drwxr-xr-x   5 johnerck  501   170 Jan 21 13:45 phpclasses
drwxr-xr-x   3 johnerck  501   102 Jan 21 13:45 psr
drwxr-xr-x   4 johnerck  501   136 Jan 21 14:28 rackspace
drwxr-xr-x   3 johnerck  501   102 Jan 21 13:45 symfony

**Comment by johnerck** [comment]
ls -al vendor/rackspace/php-opencloud/
total 0
drwxr-xr-x  2 johnerck  501   68 Jan 21 13:45 .
drwxr-xr-x  4 johnerck  501  136 Jan 21 14:28 ..

**Comment by johnerck** [comment]
When I look at the source code in my Bitbucket repo I see this:

![empty](https://cloud.githubusercontent.com/assets/1895438/5847116/8bcf8c6c-a17e-11e4-8662-29ec0dc40c06.png)

**Comment by ycombinator** [comment]
Interesting. Here's what I suggest:

1. Do not commit the `vendor` folder to your repo. You can read more about this [on the Composer FAQ](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md). As you have already committed it, please do the following to remove it:
   1. `git rm -r vendor/`
   1. `echo "vendor/" >> .gitignore`
   1. `git add .gitignore`
   1. `git commit -m 'Un-committing vendor directory and ignoring it'`
   1. `git push # You may need to specify more arguments here depending on your setup`
 
2. Re-run `php composer.phar update` and see if that populates `vendor/rackspace/php-opencloud` with files.

**Comment by johnerck** [comment]
Will do this now...

**Comment by johnerck** [comment]
YES! That worked!! Thank you so much. I do not take your help for granted. Cheers!

**Comment by ycombinator** [comment]
Glad to hear. We're here to help!
