### ISSUE TITLE
CloudFiles migrateContainer API SSL errno=32

### ISSUE THREAD

**Issue by kpedenstg** [rackspace/php-opencloud#533]
We are running PHP 5.3.10 and cURL 7.22.0.  We use the CloudFiles quite a bit for upload/download/other with lots of success.  We are now trying to use migrateContainer (because that is only way we can figure out how to rename a container) for a container with 655K objects and a size of 212GB.

We had to increase our PHP memory to 3GB and timeout to >3600.  At just under an hour, without any files being transferred (we assume migrate is building internal data structures during that time), we get the following error.  Is this a compatibility issue or migrateContainer issue or other?  Seems like cURL is used elsewhere with success.

Error: Exception encountered while transferring batch: Errors during multi transfer
(Guzzle\Http\Exception\CurlException) .../vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php line 359   [curl] 55: SSL_write() returned SYSCALL, errno = 32 [url] <and then our url which we are sure is good>.

**Comment by jamiehannaford** [comment]
@kpedenstg Hi - when I look over the ContainerMigration algorithm, it seems a bit sub-optimal. This might be a better strategy instead:

https://gist.github.com/jamiehannaford/23acf67ce008088954e2

With such a large object count - you might want to try dividing the PUT/copy operations into worker groups or something so you can take advantage of parallelism (this is up to you). Does this work better?

**Comment by kpedenstg** [comment]
Thanks Jamie.  I tried something similar using copy() before I attempted migrate but over time it kept losing its api connection after 5K files or so.  I forget now the exact error and will run it again to record it.  I can start up multiple work sessions as soon as I find a reliable method.  In the meantime, one of the side effects of this effort was  to rename a container.  Is there a straightforward way to do that?  Also, I will get back with the api connection error (if it happens again).  Thanks.

**Comment by jamiehannaford** [comment]
@kpedenstg Unfortunately there is no singular operation for renaming containers (both in OpenStack and Rackspace) :disappointed: In terms of the failed/reset connections, I recommend you using the backoff plugin which automatically retries failed connections on your behalf. This would allow you script to carry on with its execution. You will first need to install the guzzle library:

```bash
composer require guzzle/guzzle
```

and then add this to your code:

https://gist.github.com/jamiehannaford/8432889#file-add_backoff-php

**Comment by kpedenstg** [comment]
Tis sad indeed.  I have Guzzle already installed using Composer.  I also have my own retry algorithm (5 times with varying delays between each), but your Guzzle suggestion would be more efficient.  I will give it a try and post the results in the next day or two.  Thanks for your suggestions.

**Comment by jamiehannaford** [comment]
@kpedenstg Hey, are you happy for this issue to be closed? If there's anything else I can help out with, feel free to open up a new issue or e-mail our support list (sdk-support@rackspace.com).

**Comment by kpedenstg** [comment]
Thanks Jamie – You can close this.  I figured out a non-optimal solution and added a request on feedback.rackspace.com.

 

Keith

 

Standards Technology Group

Keith Peden

+1 802.764.1262

 <mailto:kpeden@standardstech.com> kpeden@standardstech.com

 <http://www.stgnet.net/> www.stgnet.net 

 

 <http://standards.stgnet.net/> standards.stgnet.net 

Using Cloud Technology to Integrate the Worlds Standards into One Shared Network

 

 <http://www.stgnet.net/> STG Logo Product - STGnet_PoweredBy_CL_SM - 0606a
