### ISSUE TITLE
Documentation: success/failure

### ISSUE THREAD

**Issue by ilithium** [rackspace/php-opencloud#536]
Hi guys

I've recently started working with your implementation of the Cloud Files API and have been working through your documentation in order to put something together, which I've done. However, I've come across one glaring problem which seems to affect ALL of your API calls:

How can I determine if the call was successful or a failure?

Could you please provide an example, or have your calls return something a bit more meaningful than a massive object structure?

Cheers!

**Comment by jamiehannaford** [comment]
@ilithium Hi Justin, I followed up over e-mail about this. Feel free to reply back over e-mail or on here and we can carry on the conversation.

**Comment by jamiehannaford** [comment]
I'm going to go ahead and close this since the issue seems to have been resolved over email. If you need help with anything else, feel free to get in touch!
