### ISSUE TITLE
cURL tries to access 127.0.0.1

### ISSUE THREAD

**Issue by ro78** [rackspace/php-opencloud#538]
Hello,

Please find my script at the end of this message.

When I run it, I receive :
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 7: couldn't connect to host [url] http://127.0.0.1:8888/v1/AUTH_...?format=json&limit=100' in /vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:359

Why is the script trying to access 127.0.0.1 ?

Best regards,
Romain
---
<?php

require 'vendor/autoload.php';

use OpenCloud\OpenStack;

// Authentification informations
$authUrl = 'https://auth.myservice.com';
$username = 'myemail';
$password = 'mypass';
$tenant = 'mytenant';
 
// Swift informations
$swiftUrl = 'https://storage.myservice.com';
$serviceName = 'swift';
$region = 'myregion';
 
// Constructor initialization
$client = new OpenStack($authUrl, array(
                    'username'    => $username,
                    'password'    => $password,
                    'tenantName'  => $tenant
                  )
              );
 
// Call the authenticate method
$client->authenticate();
 
// Send a request to the Object Store service (Swift)
$service = $client->objectStoreService($serviceName, $region, $swiftUrl);
 
// Get the containers list
$containerList = $service->listContainers();
 
// Display containers name and count the objects in each one
while ($container = $containerList->next()) {
    printf("Container name: %s\n", $container->name);
    printf("Number of objects within container: %d\n", $container->getObjectCount());
}
 
// Get all objects in the "test" container
$containerObjects = $service->getContainer('container001')->objectList();
 
// Display the name of all objects in the container
while ($containerObject = $containerObjects->next()) {
   printf("Object name: %s\n", $containerObject->getName());
}

?>

**Comment by jamiehannaford** [comment]
@ro78 Hi Romain, it looks like your service catalog is using `127.0.0.1` as base URLs for the Swift service. This depends on how you set up your OpenStack installation. To confirm, can you add this to your code and paste the output (it needs to be added after you call `$client->authenticate()`):

```php
print_r($client->getCatalog()->getItems());
```

**Comment by ro78** [comment]
You are right:
  [internalURL] => http://127.0.0.1:8888/v1/AUTH_...

Is it supposed to be fixed by my OpenStack Swift provider?

**Comment by jamiehannaford** [comment]
@ro78 In order to access Swift on `127.0.0.1` you will need to run the script from an OpenStack compute instance which is *inside* the region you're accessing. Otherwise, you will need to use a public URL. What happens when you try:

```php
$service = $client->objectStoreService('swift', 'myregion');
```

**Comment by ro78** [comment]
Perfect! Thanks!
