### ISSUE TITLE
Calls to getContainer take twice as long as a raw curl call

### ISSUE THREAD

**Issue by nickjenkin** [rackspace/php-opencloud#540]
I can give you an xhprof dump if required, it looks like this might be guzzle related, however this is pretty annoying. Strangely we do not seem to be having issues with Container->getObject() calls

(maybe also for the rackspace side: why is this api so slow in general?)

[vagrant@localhost log]$ time mr rackspace test-speed-curl
Operation Successful

real	0m6.887s
user	0m5.032s
sys	0m0.455s
[vagrant@localhost log]$ time mr rackspace test-speed
Operation Successful

real	0m12.610s
user	0m1.997s
sys	0m1.743s

```php
function cf_test_speed() {
    $cf = Cloudfiles_client();
    $cf->getContainer('PTS');
}

function cf_test_speed_curl() {

    $cf = Cloudfiles_client();
    $client = $cf->getClient();
    $token = $client->getToken();

    $ch = curl_init();
    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt ($ch, CURLOPT_URL, "https://storage101.ord1.clouddrive.com/v1/MossoCloudFS_XXXX/PTS");
    curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, 20);
    curl_setopt ($ch, CURLOPT_USERAGENT, 'rk');

    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'HEAD');
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'X-Auth-Token: ' . $token));
    $content = curl_exec ($ch);
    curl_close ($ch);

}

```

**Comment by nickjenkin** [comment]
Perhaps this is for another issue, but it would be great if the object store service exposed a direct getFile method rather than having to make 2 calls to get a file.

Alternatively, the HEAD request in getContainer is not required in order to get a file, so it seems completely unnecessary performance wise to do it unless the metadata is required.

**Comment by ycombinator** [comment]
Hi @nickjenkin, I'm investigating the performance difference between using curl and using the SDK to retrieve a container.

**Comment by ycombinator** [comment]
I turned on [debugging in the SDK](https://github.com/rackspace/php-opencloud/blob/working/docs/userguide/Debugging.md#strategy-2-wire-logging) and right away noticed something. When `getContainer()` is called, _two_ HTTP requests are made - one to the container's regular URI and another to the container's CDN URI. This happens regardless of whether the container is CDN-enabled or not.
