### ISSUE TITLE
Use guzzle/guzzle instead of various guzzle/* packages

### ISSUE THREAD

**Issue by ycombinator** [rackspace/php-opencloud#541]
When trying to install php-opencloud via composer, warnings are thrown about the various guzzle/* packages being abandoned:

```
$ composer require rackspace/php-opencloud
Using version ~1.12 for rackspace/php-opencloud
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.6.4)
    Loading from cache

  - Installing guzzle/common (v3.9.2)
    Loading from cache

  - Installing guzzle/stream (v3.9.2)
    Loading from cache

  - Installing guzzle/parser (v3.9.2)
    Loading from cache

  - Installing guzzle/http (v3.9.2)
    Loading from cache

  - Installing rackspace/php-opencloud (v1.12.1)
    Loading from cache

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files
```

This task is to make php-opencloud use `guzzle/guzzle` in place of the various `guzzle/*` packages.

**Comment by jamiehannaford** [comment]
@ycombinator This would also reduce the burden when debugging too, since we often have to instruct the user to run `composer install guzzle/guzzle`. If the whole dependency is installed by default, it's one less step to worry about - so :+1: from me

**Comment by ycombinator** [comment]
Fixed in #544.

**Comment by simon-lifelike** [comment]
Would it be possible to get a stable tagged release for this @ycombinator? Having abandoned dependencies in production makes me anxious, and from what I understand it's mainly a namespace change (same version has the same api's), so it would still comply with a semver patch release (if that's what you're going for).

**Comment by ycombinator** [comment]
Hi @simon-lifelike, absolutely. We plan to cut a new release either today or Monday. I'll let you know here when it is done.

**Comment by ycombinator** [comment]
FYI, our release is currently blocked by https://github.com/rackspace/php-opencloud/issues/560. Once that is resolved (or we are comfortable working around it), we will cut a new release.

**Comment by ycombinator** [comment]
Hi @simon-lifelike, I have just cut a new release &mdash; v1.12.2.

* On Packagist (for download via Composer): https://packagist.org/packages/rackspace/php-opencloud#v1.12.2
* Release notes: https://github.com/rackspace/php-opencloud/releases/tag/v1.12.2

**Comment by simon-lifelike** [comment]
Fantastic, thanks for keeping me posted!

**Comment by simon-lifelike** [comment]
Could we re-open this issue? Seems like it got changed back again :disappointed:

**Comment by jamiehannaford** [comment]
@simon-lifelike Hmm, that should not have happened. I'll submit a PR now - thanks for the catch!

**Comment by jamiehannaford** [comment]
@simon-lifelike Can you upgrade to v1.14.1 and let me know if it's okay?

**Comment by simon-lifelike** [comment]
Perfect, all good now. Thanks for the fast response!
