### ISSUE TITLE
Possible to get DataObject from Guzzle response?

### ISSUE THREAD

**Issue by shanebonham** [rackspace/php-opencloud#545]
Hi there,

`OpenCloud\ObjectStore\Resource\Container::uploadObjects()` returns an array of Guzzle responses (in contrast to `uploadObject()` which returns a `DataObject`).

Is it possible to get the `DataObject` from a Guzzle response? I need to upload a batch of files, but then store each file's public URL.

**Comment by ycombinator** [comment]
Unfortunately there is no direct way to do this with the SDK. However, the following snippet of code should get you what you need, assuming you had the line `$responses = $container->uploadObjects($objects)`:

```php
foreach ($responses as $index => $response) {
    $dataObject = $container->dataObject()
        ->populateFromResponse($response);
    $dataObject->setName($objects[$index]['name']);
    echo $dataObject->getPublicUrl();
}
```

**Comment by shanebonham** [comment]
Thank you, that is very helpful!
