### ISSUE TITLE
Smoke tests for Databases fail with SSL error

### ISSUE THREAD

**Issue by ycombinator** [rackspace/php-opencloud#560]
While trying to cut a new release, I ran all smoke tests. The Cloud Databases smoke tests immediately failed:

```
$ php tests/OpenCloud/Smoke/Runner.php --include=Database
Welcome to the PHP OpenCloud SmokeTest!

Authenticate
   Using identity endpoint: https://identity.api.rackspacecloud.com/v2.0/
   Using region: IAD
   Token generated: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Executing OpenCloud\Smoke\Unit\Database

   1. Get Flavors
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://iad.databases.api.rackspacecloud.com/v1.0/XXXXX/flavors/detail?limit=100' in /root/php-opencloud/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
```

**Comment by ycombinator** [comment]
`curl`ing the Cloud Databases endpoint from the command line also produces a similar error:

```
$ curl https://iad.databases.api.rackspacecloud.com/
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by ycombinator** [comment]
BTW, versions of `curl` and `openssl` on the machine where I ran the smoke tests from are:

```
$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

```
$ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by ycombinator** [comment]
Even after upgrading OpenSSL to 1.0.2, I still get the same curl error:

```
$ openssl version
OpenSSL 1.0.2 22 Jan 2015

$ curl https://iad.databases.api.rackspacecloud.com
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by ycombinator** [comment]
BTW, I'm on Ubuntu 14.04:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
```

**Comment by ycombinator** [comment]
Paging @dstufft. Could you please help us figure out what might be going on here and how best we should fix it? Thanks.

**Comment by dstufft** [comment]
Almost certainly this is caused because RC4 is insecure and broken and nobody should rely on it. I'm pretty sure that Linux distros are shipping updates which default to no longer using RC4. Then the iad.databases.api.rackspacecloud.com endpoint comes along and *only* supports RC4.

**Comment by ycombinator** [comment]
We had some out-of-band discussion on the team and agreed to override the curl options just for the Cloud Databases service to use the TLSv1 cipher suite. This is meant to be temporary until the service can support more secure ciphers than RC4.

**Comment by dstufft** [comment]
Cipher String:

```
ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:DH+HIGH:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+HIGH:RSA+3DES:ECDH+RC4:DH+RC4:RSA+RC4:!aNULL:!eNULL:!MD5
```

This Cipher list has been carefully constructed to result in a specific set of
ciphers in a specific order. This list has been constructed to exclude any
unsafe ciphers with the exception of RC4, which is currently weak but still
required for compatability with many services.

The string translates to a cipher suite list which is roughly:

* AES GCM using the ECDHE Key Exchange, then the DHE Key Exchange.
* AES 256 using the ECDHE Key Exchange, then the DHE Eey Exchange.
* Any AES using the ECDHE Key Exhcange, then the DHE Key Exchange.
* Any "HIGH" security cipher using the ECDHE Key Exchange, then the DHE Key
  Exchange.
* 3DES using the EXDHE Key Exhcnage, then the DHE Key Exchange.
* Any AES GCM using the RSA Key Exchange (No PFS).
* Any AES using the RSA Key Exchange (No PFS).
* Any "HIGH" cipher using the RSA Key Exchange (No PFS).
* Any 3DES cipher using the RSA Key Exchange (NO PFS).
* Any RC4 cipher preferring those with ECDHE, then DHE, then RSA Key exchanges.

Finally it explicitly disallows:

* Any cipher that does not include authentication.
* Any cipher that does not include encryption.
* Any cipher that uses a MAC based on MD5.

**Comment by ycombinator** [comment]
We will be using the cipher suite mentioned in the previous comment until the Rackspace Cloud Servers service stops supporting RC4 and starts supporting stronger ciphers instead.
