### ISSUE TITLE
Allow DNS domain retrieval by name

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/php-opencloud#572]
... rather than an unknown ID.

Currently, the only way to do this is something like this:

```php
$search = "mydomain.com";
$domainList = $service->domainList(array("name"=>$search));
foreach($domainList as $domain) {
    $id = $domain->id();
}
```

Feature requested by @joshrencher (mentioning you here so you can keep track of this request).

**Comment by ycombinator** [comment]
Currently, the only way to do this is something like this:

```php
$search = "mydomain.com";
$domainList = $service->domainList(array("name"=>$search));
foreach($domainList as $domain) {
    $id = $domain->id();
}
```

**Comment by joshrencher** [comment]
Thank you!

**Comment by ycombinator** [comment]
Hey @jamiehannaford, I know you added this to the v2 milestone but I took a crack at it in v1 anyway. I've submitted PR #574. Feel free to close it unmerged if you think we should add this convenience method exclusively in v2. Thanks.

**Comment by jamiehannaford** [comment]
@joshrencher There should now be a new method called [`domainByName`](https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/DNS/Service.php#L65-L74) in `dev-working` which @ycombinator has added. Hopefully this is more convenient :)

**Comment by joshrencher** [comment]
absolutely more convenient. thanks guys!
