### ISSUE TITLE
Support availability zones on compute servers

### ISSUE THREAD

**Issue by ycombinator** [rackspace/php-opencloud#575]
See optional `availability_zone` request parameter in the [create server API](http://developer.openstack.org/api-ref-compute-v2.html)

**Comment by slashterix** [comment]
Thanks! Can this also be done for Cinder Volumes?

**Comment by ycombinator** [comment]
@slashterix Added https://github.com/rackspace/php-opencloud/issues/577 to track this functionality for Cinder Volumes.
