### ISSUE TITLE
[ Enhancement ] Upgrade Guzzle to GuzzleHttp

### ISSUE THREAD

**Issue by virgofx** [rackspace/php-opencloud#586]
Update required Guzzle dependencies to the newer GuzzleHttp

**Comment by GrahamCampbell** [comment]
That's quite a big task.

**Comment by jamiehannaford** [comment]
@virgofx Yeah, as @GrahamCampbell said, it's a big task. This has been on my radar for a long time - but we can't implement into v1 since upgrading this dependency would be a breaking change, requiring a major version bump. I've been working on a [v2 prototype](https://github.com/php-opencloud/openstack-prototype-v3) recently which will utilize the new Guzzle packages; release ETA is a month or so. I'd love to get your feedback about what other things you'd like to see in v2 - feel free to submit issues with feature requests or enhancements.

**Comment by virgofx** [comment]
@jamiehannaford  Is the new php-opencloud group the new hub for future dev/work for related php/opencloud/rackspace?  I don't mind the switch as it's probably necessary to deal with all the BC changes. I just remember when we switched a couple years ago to the current  rackspace / php-opencloud  from (can't remeber -- something more SDK specific).  

Or is it a temporary playground until you merge into 2.0 in the current repository?

**Comment by jamiehannaford** [comment]
@virgofx Yes, [php-opencloud/openstack](https://github.com/php-opencloud/openstack) is the repo for all the OpenStack SDK 2.x work. So far we have Identity v2, Identity v3, Compute v3, Object Store v1 and some Networking. I'm not sure where the Rackspace repo will be yet - either in the `php-opencloud` or `rackspace` orgs - but it will probably extend the base `openstack` repo.

There's no hard ETA yet, but I'll try and write migration guides for users porting from 1.x to 2.x. If you'd like to contribute to the new SDK (or even just provide feedback), you're more than welcome :+1:

**Comment by sneakyimp** [comment]
guzzle/guzzle has been deprecated now:
https://packagist.org/packages/guzzle/guzzle

**Comment by mendrinos** [comment]
@jamiehannaford 

Any update on this? It's been 1 year we are having this deprecated:
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by jamiehannaford** [comment]
@mendrinos We will not be upgrading this v1 SDK to the newer Guzzle versions. There's already a v2 OpenStack SDK which uses the new dependency. The v2 Rackspace SDK is in the works.

**Comment by mendrinos** [comment]
@jamiehannaford  Thanks for the clarification!

**Comment by redthor** [comment]
FWIW I've updated the dependencies in this branch:
https://github.com/redthor/php-opencloud/tree/fix/guzzlehttp
and the unit tests pass. I don't have an opencloud account so I haven't tried the acceptance tests.

I only tried it due to https://github.com/KnpLabs/Gaufrette/issues/426

**Comment by drjonnicholson** [comment]
Thanks to @jamiehannaford for explaining the roadmap and that updating this dependency will not be done in v1.

Just wondering if there is there any update as yet on when V2 is expected to be released?

**Comment by sneakyimp** [comment]
#Crickets. Doesn't look like we'll ever get a new version -- at least not here. Hannaford said above one would be ready around mid-May 2015 (almost two years ago). He apparently moved the project [here](https://github.com/php-opencloud/openstack) but he also said 5 months ago that 

>The v2 Rackspace SDK is in the works.

Any suggestions about how to proceed would be helpful. I'm working on a project that uses the Rackspace cloud and need something stable that will ideally last about five years.

**Comment by jamiehannaford** [comment]
Imp, feel free to use the [v2](https://github.com/rackspace/php-opencloud/tree/v2) branch or adapt what you need from the openstack SDK. I do not maintain this project any more. For SDK questions please contact sdk-support@rackspace.com.

**Comment by sneakyimp** [comment]
"nothing to see here."

BTW, official word from rackspace is that "V2 is not being actively developed." Rackspace still references this now-dead and not-being-updated from their [documentation](https://developer.rackspace.com/sdks/php/)

This is totally, completely lame.
