### ISSUE TITLE
Add support for Identity v3

### ISSUE THREAD

**Issue by stenstad** [rackspace/php-opencloud#587]
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Currently OpenCloud does not work with providers that require support for Identity v3.

This was recently added to Gophercloud, so that consumers like Packer.IO and Docker Machine work with v3 providers.

Would it be possible to add support for Identity v3 in this project as well?

**Comment by jamiehannaford** [comment]
@stenstad Sure. I'm in the middle of writing the [v2 SDK](https://github.com/php-opencloud/openstack) at the moment, so I might focus efforts of implementing Keystone v3 before v2 and making it the default identity service. Thanks for the heads up; I'll keep you updated with progress.

**Comment by alewitt** [comment]
Has anything come of this issue? i need to use keystone v3 in a php project.

**Comment by jamiehannaford** [comment]
@alewitt Keystone v3 is the default in the [new SDK](https://github.com/php-opencloud/openstack), but it's not 100% production-ready yet. I still need to add support for Cinder and Glance, but feel free to use.

**Comment by alewitt** [comment]
thanks!!

**Comment by alewitt** [comment]
I tried composer require on the new sdk, but it can't find the package because the project hasn't been added to packagist yet. So for now i think i can just link straight to the github repo. Just an fyi

**Comment by jamiehannaford** [comment]
@alewitt I just added it, so you should be able to use `php-opencloud/openstack:dev-master` now. Thanks for the heads up

**Comment by alewitt** [comment]
thanks!
