### ISSUE TITLE
Can't get this working with OVH Runabove

### ISSUE THREAD

**Issue by shealan** [rackspace/php-opencloud#588]
Does anyone have a working example of this package working with Runabove they could share as a gist? I can't seem to get this package to work at all (401 errors) and their documentation is pretty woeful.

**Comment by jamiehannaford** [comment]
@shealan Are you following the [OpenStack getting started guide](http://docs.php-opencloud.com/en/latest/getting-started-with-openstack.html)? I would assume that they're using some variety of vanilla OpenStack, so that's probably your best bet. 

Could you enable the [wire logging plugin](http://docs.php-opencloud.com/en/latest/debugging.html#strategy-2-wire-logging) and send the output to jamie.hannaford@rackspace.com and I'll investigate.

**Comment by notFloran** [comment]
I made a gist with an example to create a server : https://gist.github.com/notFloran/60d6095443078eee8884

**Comment by DSpeichert** [comment]
You can check out #564, where we documented our config and you might also see a problem that occurs with RunAbove.

**Comment by shealan** [comment]
Thanks for the input guys but I always get a 401 error even with that Guzzle "hack". Here is my test code (Laravel 5) and the log. I'm trying to use the object store.

```
use OpenCloud\OpenStack;
use Guzzle\Http\Exception\BadResponseException;
use Guzzle\Plugin\Log\LogPlugin;

Route::get('openstack', function() {

	$client = new OpenStack('https://auth.runabove.io/v2.0/', array(
	    'username' => 'my@email.com',
	    'password' => 'XXXXXXXXX',
	    'tenantId' => '12345678' 
	));

	$client->addSubscriber(LogPlugin::getDebugPlugin());

	$service = $client->objectStoreService('test', 'SBG-1');

	$container = $service->getContainer('podlaunchtest');

	$container->uploadObject('test.txt', fopen('../public/test.txt', 'r+'));

});
```

Here's the log:

```
# Request: POST /v2.0/tokens HTTP/1.1 Host: auth.runabove.io Content-Type: application/json User-Agent: OpenCloud/1.9.0 cURL/7.37.1 PHP/5.6.6-1+deb.sury.org~utopic+1 Accept: application/json X-Auth-Token: Content-Length: 123 {"auth":{"passwordCredentials":{"username":"my@email.com","password":"XXXXXXXXX"},"tenantId":"12345678"}} # Response: HTTP/1.1 401 Unauthorized Vary: X-Auth-Token Content-Type: application/json Date: Thu, 30 Apr 2015 08:27:23 GMT Transfer-Encoding: chunked {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}} # Errors: 0
```

**Comment by jamiehannaford** [comment]
@shealan It seems like the actual auth call is failing for some reason - are you sure you're using the correct username, password and tenantName for your account? If so, I suggest contacting the RunAbove support to see if it's an access issue. All the SDK does it connect to an API and transact data; if the API is refusing access, there's not much to do apart from contacting their team.

**Comment by shealan** [comment]
@jamiehannaford thanks for the input. I've checked and re-checked credentials. Perhaps it's because I haven't "validated" my account. I have just sent them a passport scan and explanation of my project. I can't see any mention anywhere that API access is blocked until this is done but I suppose it's a possibility.

**Comment by jamiehannaford** [comment]
@shealan Yeah. With OpenStack Keystone (their auth service), it's possible to [disable or enable](http://docs.openstack.org/user-guide-admin/adminuser/manage_projects_users_and_roles.html) a user account - so I'd double check with them first. If it's something API or SDK related, I'll more than happily investigate any related cause.

**Comment by jamiehannaford** [comment]
@shealan Am I okay to close this? Do you need any more help with using the SDK?

**Comment by shealan** [comment]
Never got it working but I suspect it is something to do with Runabove rather than the library. Can close.

**Comment by fdjohnston** [comment]
@shealan Just wanted to pop in here and say I was having the same issue, but I figured it out.
If you log into the Run Above Horizon panel, then go "Access & Security", then to the API access tab, you'll see an object store URL in there, and maybe one for compute, etc.  Mine looks like:
https://storage.sbg-1.runabove.io/v1/AUTH_{big long number}

That {big long number} is the tentantId you want to use... not the Current Project Id they display in the top left.

Hope that helps.

**Comment by shealan** [comment]
@fdjohnston thank you very much for this useful bit of information, I was indeed using the project ID :)
