### ISSUE TITLE
Unable to select CDN Container

### ISSUE THREAD

**Issue by mirahost** [rackspace/php-opencloud#591]
I can successfully connect and list all CDN Containers, but I am unable to select a specific container.             

    self::$service = $client->objectStoreService(Config::get('opencloud.service'), Config::get('opencloud.location'), Config::get('opencloud.urltype'));
    self::$cdnService = self::$service->getCdnService();
    
    $cdnContainers = self::$cdnService->listContainers();

Each container shows its name, metadata, with uris, and that cdn is enabled.

However, if I attempt to get a specific container I get the following:

    $container = self::$cdnService->cdnContainer('containerName');

ErrorException [ Notice ]: Trying to get property of non-object

/Library/WebServer/Documents/private/vendor/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/CDNService.php @ line 59:

58:	$metadata->setArray(array(
59:	'Streaming-Uri' => $data->cdn_streaming_uri,
60:	'Ios-Uri' => $data->cdn_ios_uri,

This continues for each object in the metadata array.

In the ObjectStore/CDNService.php file where function cdnContainer is called. I tried dumping the $data passed to it and it's a string with the container name. $data doesnt contain the metadata values it is trying to set.

 public function cdnContainer($data)
    {   
        $container = new CDNContainer($this, $data);

        $metadata = new ContainerMetadata();
        $metadata->setArray(array(
            'Streaming-Uri' => $data->cdn_streaming_uri,
            'Ios-Uri' => $data->cdn_ios_uri,
            'Ssl-Uri' => $data->cdn_ssl_uri,
            'Enabled' => $data->cdn_enabled,
            'Ttl' => $data->ttl,
            'Log-Retention' => $data->log_retention,
            'Uri' => $data->cdn_uri,
        ));

        $container->setMetadata($metadata);

        return $container;
    }

**Comment by jamiehannaford** [comment]
@mirahost Hi, what happens when you try this:

```php
// Instantiate from ObjectStore service, not CDN service
$container = self::$service->getContainer('containerName');

// Get CDN container
$cdnContainer = $container->getCdn();

echo $cdnContainer->getCdnStreamingUri();
```

**Comment by mirahost** [comment]
@jamiehannaford Thank you for the assistance with this. When I execute the code you provided it returns the streaming URL.
Do you know why the other method doesnt work? Is there a means to get the list of objects in a CDN container?

**Comment by jamiehannaford** [comment]
@mirahost What happens when you try:

```php
$objects = $container->objectList();
```

If you execute that method on a CDN-enabled container, it will return all the objects. You will need to ensure the container is actually CDN-enabled first. You can use `$container-> isCdnEnabled()` for that.

**Comment by mirahost** [comment]
That works. I was making the mistake of using the cdn container connection. The docs could use some clarity in this department. 

Thank you for your prompt assistance.

**Comment by jamiehannaford** [comment]
@mirahost Glad to hear that worked! Yeah, you're right. Can you link me to the doc pages you were using? I'll get them updated ASAP. 

Closing this issue since it's been resolved.

**Comment by mirahost** [comment]
I think the confusion happened here:
http://php-opencloud.readthedocs.org/en/latest/services/object-store/cdn.html
Specifically this part:
"In order to interact with CDN containers, you first need to instantiate a CDN service object:"
    $cdnService = $service->getCdnService();

That got me thinking I needed to execute the commands after making the cdnService connection.
But based on the code you provided above, that is not the case. I dont see this method listed:
    $cdnContainer = $container->getCdn();
