### ISSUE TITLE
UploadDirectory

### ISSUE THREAD

**Issue by Uniphix** [rackspace/php-opencloud#608]
When I use this function I expected it to do this.

uploadDirectory('/var/www/html/js') will dump ALL the content inside of "MyContainer" rather than dumping it directly to "MyContainer" -> Inside of js folder of that container.  

It'd be nice to be able to specifically mention what folder you want to upload to inside of the Container.  Aka maybe you have '/var/www/html/js/' as a path but you want it to be dumped into 'MyContainer/html/js' or something... so you would maybe do something like

uploadDirectory(localPath, toPathInContainer) (where to path in container is an optional parameter if it is not set then use the default concept.)

**Comment by jamiehannaford** [comment]
@Uniphix Thanks for the suggestion! I've just merged this feature into the `working` branch. Would you mind testing it to see whether it does what you need it to? You will need to update your composer version to `dev-working`.
