### ISSUE TITLE
RE: Repository history

### ISSUE THREAD

**Issue by AlekseyKorzun** [rackspace/php-opencloud#612]
Obviously you guys spend way more time on this than I did. Great job.

I'm just curious if at any point code from https://github.com/AlekseyKorzun/rackspace-open-cloud-php was used as a reference? The time stamps on that repository are changed because it was moved around a bit. Original release was in 2009.

This is not an accusation of any sort; but there are certain things that are a kind of similar. You also use new approach (collections, etc) just like my API client for Twilio. 

I don't have any hard evidence because anything that I was able to match can be written off. 

If you did look at some of my clients, a mention would be nice. Otherwise feel free to close this out.

Thanks.

**Comment by jamiehannaford** [comment]
No, I've never seen your repository before. I'm working on a new [v2 library](https://github.com/php-opencloud/openstack) that moves away from our v1 work. Feel free to join in if you want to, all contributions are welcome.

**Comment by AlekseyKorzun** [comment]
That's fine; @jamiehannaford. You do have have multiple contributions to this repository from multiple people so I don't think it matters of if you seen my repository (from 2009) before. I saw cloud file stuff Rackspace had before and it definitely had some of my code (that was later pivoted to php-opencloud) and never said a thing.

Anyways, moving on.
