### ISSUE TITLE
EndpointError thrown when instantiating CDN service

### ISSUE THREAD

**Issue by rchouinard** [rackspace/php-opencloud#614]
Attempting to retrieve a CDN service instance from `OpenCloud\Rackspace` results in an `OpenCloud\Common\Exceptions\EndpointError` exception. The only workaround I've found which seems to work consistently is to hard-code the region to DFW when requesting the service instance.

Either the API or the CDN service class seem to be somehow broken when detecting or handling the region flag for this service.

### Versions
Both v1.14.2 and dev-master@dev yield the same results.

### Base code
```php
<?php

require __DIR__ . "/vendor/autoload.php";

use OpenCloud\Rackspace;

$client = new Rackspace(Rackspace::US_IDENTITY_ENDPOINT, array(
    "username"  => MY_RS_USERNAME,
    "apiKey"    => MY_RS_APIKEY,
));

$cdnService = $client->cdnService();
```

###### Result
    Fatal error: Uncaught exception 'OpenCloud\Common\Exceptions\EndpointError' with message 'This service [rackCDN] does not have access to the [] endpoint.' in vendor\rackspace\php-opencloud\lib\OpenCloud\Common\Service\CatalogItem.php on line 151

#### Default region
Attempting to utilize the authenticated user's default region works for some users and not for others. The result on failure is the same exception with a slightly different message based on the user's default region.

```php
<?php

require __DIR__ . "/vendor/autoload.php";

use OpenCloud\Rackspace;

$client = new Rackspace(Rackspace::US_IDENTITY_ENDPOINT, array(
    "username"  => MY_RS_USERNAME,
    "apiKey"    => MY_RS_APIKEY,
));

$client->authenticate();
$cdnService = $client->cdnService(null, $client->getUser()->getDefaultRegion());
```

##### Result
    Fatal error: Uncaught exception 'OpenCloud\Common\Exceptions\EndpointError' with message 'This service [rackCDN] does not have access to the [IAD] endpoint.' in vendor\rackspace\php-opencloud\lib\OpenCloud\Common\Service\CatalogItem.php on line 151

Curiously, users with the default region of DFW always seem to work, which led to testing the next variation.

#### Hardcode region
Hard coding the region to `DFW` appears to work for all the accounts tested, but this may be an unsafe assumption in production; Non-US based accounts would likely not work, for example.

```php
<?php

require __DIR__ . "/vendor/autoload.php";

use OpenCloud\Rackspace;

$client = new Rackspace(Rackspace::US_IDENTITY_ENDPOINT, array(
    "username"  => MY_RS_USERNAME,
    "apiKey"    => MY_RS_APIKEY,
));

$cdnService = $client->cdnService(null, "DFW");
```

##### Result
Operations on `$cdnService` function as expected.

**Comment by jamiehannaford** [comment]
@rchouinard It seems that the new CDN service is only available in `DFW` so far, and no other region. So if you rely on your default region or specifying anything other than `DFW` a fatal error will be raised because the SDK cannot retrieve the base URL from the service catalog.

**Comment by jamiehannaford** [comment]
@rchouinard I've submitted a fix for this (#615)

**Comment by rchouinard** [comment]
@jamiehannaford  I figured it was something like that, but of course this means that the library won't work as documented for accounts with default regions other than DFW.

Thank you for the quick response and PR.

**Comment by jamiehannaford** [comment]
@rchouinard Would you mind checking to see whether the `dev-working` branch fixes your problem?

**Comment by jamiehannaford** [comment]
@rchouinard Am I okay to close this?

**Comment by poorman** [comment]
you can close it, it works for me. I had same issue. I updated my files manually. composer update doesn't do anything.

**Comment by jamiehannaford** [comment]
@poorman Did you change your version to `dev-working` in composer.json? If not, it will just try updating to the most recent published release (which doesn't have this change yet).

**Comment by poorman** [comment]
thanks for that @jamiehannaford, I thought it was merged and pushed live.

**Comment by poorman** [comment]
@jamiehannaford btw, do have any examples how to purge specific list of files from rackspace cdn?

**Comment by jamiehannaford** [comment]
@poorman Yeah, we have one for [purging a specific asset](https://github.com/rackspace/php-opencloud/blob/working/samples/CDN/purge-cached-service-asset.php), and another for [purging all the assets for a service](https://github.com/rackspace/php-opencloud/blob/working/samples/CDN/purge-cached-service-assets.php).

**Comment by poorman** [comment]
@jamiehannaford last question.
Where can I get '{serviceId}') and does {assetUrl} should look like /cdn/textfile.txt or with domain like cdntest.domainname.com/cdn/textfile.txt

Thank You!!!


----------- i listed services and cannot find service id ----------

$service = $cdnService->getService(0);

	echo var_dump($service);
	
	/*foreach ($services as $service) {
		echo $counter;
		$counter++;
	}*/

**Comment by jamiehannaford** [comment]
@poorman To retrieve your service ID, you can list services:

```php
$services = $cdnService->listServices();

foreach ($services as $service) {
   if ($service->getName() == 'mywebsite.com') {
      $serviceId = $service->getId();
      break;
   }
}
```

The `{assetUrl}` should be in the form of `/cdn/textfile.txt`.
