### ISSUE TITLE
404 error when calling uploadObject on a new container

### ISSUE THREAD

**Issue by alexjeen** [rackspace/php-opencloud#616]
It must be something dead simple, but I am getting a 404 error calling uploadObject on a "fresh" container (ie. it was just created).

I create my upload container;

    $upload_container = $model->create_os_container($model->client_id);

The code for create_os_container is:

    public function create_os_container($client_id)
    {
        $connection = $this->setup_os_connection();

        $ostore = $connection->objectStoreService("swift", "NL", "publicURL");

        $container_found = null;

        try
        {
            $container_found =  $ostore->getContainer('client_' . $client_id);
        }
        catch(Exception $e)
        {
            // get container throws a 404 if the container does not exist
            $ostore->createContainer('client_' . $client_id);
        }

        if(!$container_found)
        {
            return $this->create_os_container($client_id);
        }

        return $container_found;
    }

The code works fine, if the container already exists. But if it's a new container and I upload using;

    $upload_container->uploadObject($filename, file_get_contents($tmp));

I get the following Exception:

    Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
    [status code] 404
    [reason phrase] Not Found
    [url] urltothefilehere

The next time you try to upload a file to the container, it works fine. If you need a stacktrace I can provide it. 

Maybe it's something dumb like the return value of getContainer.

**Comment by jamiehannaford** [comment]
@alexjeen Hmm, strange. The return value of `create_os_container` must be a container (which indicates the create call was successful) otherwise you'd get a fatal exception about not being able to call `uploadObject` on `NULL`. 

Could you turn on [HTTP wire logging](http://docs.php-opencloud.com/en/latest/debugging.html#strategy-2-wire-logging) and send it to jamie.hannaford@rackspace.com?

**Comment by alexjeen** [comment]
Turns out this has to do with the implementation of the OpenStack provider. We don't use Rackspace but CloudVPS. 

CloudVPS has slow hardware that causes this issue.

Migrated to Rackspace and issue is resolved.
