### ISSUE TITLE
Unable to set ServerMetaData

### ISSUE THREAD

**Issue by mc388** [rackspace/php-opencloud#625]
I try to add some metadata to a server with the following code: 

```
/** @var \OpenCloud\Compute\Resource\Server $server */
$server = $this->service->server($id);

/** @var \OpenCloud\Compute\Resource\ServerMetadata $metaData */
$metaData = $server->metadata();
$metaData->__set("some_key", "some_value");
$metaData->create();
```

The `create()` method in `\OpenCloud\Compute\Resource\ServerMetadata`  calls `getMetadataJson()`. There the metadata should add to a new object which will be json encoded. But in this method something is wrong. Only  the medadata value is stored and not the key-value-pair. In my example the metadata-object looks like: `"some_value" => ""`. This brings up two problems:
1. You are not able to get the value from a given key
2. After adding new metadata you get an exception in line [184](https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Compute/Resource/ServerMetadata.php#L184) `Cannnot access empty property`.

I think the easiest way is to replace the foreach in line [183](https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Compute/Resource/ServerMetadata.php#L183) with `$object->metadata = $this->keylist();`

After this change the metadata are stored correctly.

**Comment by jamiehannaford** [comment]
@mc388 thanks for reporting this. I've pushed a fix to `working`. Can you point your Composer dependency to `dev-working` and let me know if it works for you?

**Comment by mc388** [comment]
@jamiehannaford thank you for the very quick fix. I referenced the `working` branch in my composer file and it works fine. Thanks a lot!
