### ISSUE TITLE
list servers strange

### ISSUE THREAD

**Issue by joubertredrat** [rackspace/php-opencloud#632]
Hi guys,

I'm testing this sdk here and Identity works fine, but I'm with problems about Compute Service.

PHP Opencloud documetation and example show how to list servers, as in http://docs.php-opencloud.com/en/latest/services/compute/servers.html#list-servers and https://github.com/rackspace/php-opencloud/blob/working/samples/Compute/list_servers.php

But in my test this don't work, display this exception
```
[curl] 52: Empty reply from server [url] http://nova.mydomain:8774/v2/03932c400ac947eb8a60f17fda9a28b9/servers/82c562dc-7cdc-4092-85b4-aeca6d9b3b4a/metadata
```

But this is strange, because on catalog my nova API is correct on https and not in http
```
      array(4) {
        ["endpoints"]=>
        array(1) {
          [0]=>
          array(5) {
            ["adminURL"]=>
            string(59) "http://10.161.1.81:8774/v2/03932c400ac947eb8a60f17fda9a28b9"
            ["region"]=>
            string(9) "regionOne"
            ["internalURL"]=>
            string(59) "http://10.161.1.81:8774/v2/03932c400ac947eb8a60f17fda9a28b9"
            ["id"]=>
            string(32) "6e4643457b45479990796e31e74674f0"
            ["publicURL"]=>
            string(78) "https://nova.mydomain:8774/v2/03932c400ac947eb8a60f17fda9a28b9"
          }
        }
        ["endpoints_links"]=>
        array(0) {
        }
        ["type"]=>
        string(7) "compute"
        ["name"]=>
        string(7) "compute"
      }
```

Another strange is, Service class display that serverList return class PaginatedIterator as in https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Compute/Service.php#L105
I'm looking here, PaginatedIterator class extends from ResourceIterator class, ResourceIterator class extends from ArrayCollection.

Looking on ArrayCollection, why have setElements method and not getElements? On my test worked fine with this implementation, with array with servers as stdClass.

```PHP
<?php
    /**
     * OpenCloud/Common/Collection/ArrayCollection.php
     * @return $array
     */
    public function getElements()
    {
        return $this->elements;
    }
```
```PHP
require 'vendor/autoload.php';

$client = new OpenCloud\OpenStack('https://keystone.mydomain:5000/v2.0', array(
  'username' => 'myusername',
  'password' => 'mypassword',
  'tenantId' => 'mytennant',
));

$service = $client->computeService('compute', 'regionOne', 'publicURL');
$serverList = $service->serverList();
var_dump($serverList->getElements());

/*
array(2) {
  [0]=>
  object(stdClass)#130 (27) {
    ["status"]=>
    string(6) "ACTIVE"
    ["updated"]=>
    string(20) "2015-09-17T21:07:16Z"
    ["hostId"]=>
    string(56) "e50b9897745626c1462b3a342b275064e011308a40f1a2457a3b65a1"
    ["addresses"]=>
    object(stdClass)#144 (1) {
      ["privada"]=>
      array(1) {
        [0]=>
        object(stdClass)#145 (4) {
          ["OS-EXT-IPS-MAC:mac_addr"]=>
          string(17) "fa:16:3e:3a:4b:91"
          ["version"]=>
          int(4)
          ["addr"]=>
          string(11) "10.56.44.14"
          ["OS-EXT-IPS:type"]=>
          string(5) "fixed"
        }
      }
    }
    ....
*/
```

Then I have 2 questions

1 - Is a bug on SDK when I try to get server data and SDK tried to get from wrong http://mydomain instead of https://mydomain or is wrong from my API? I will try to discover with bug trace here.

2 - Isn't necessary method getElements() on ArrayCollection class?

Thanks for all

**Comment by joubertredrat** [comment]
Hi guys,

About first question, is really bug on my API, then I solved this, now about second question, what you think?

**Comment by jamiehannaford** [comment]
@joubertredrat What is your use case for requiring the entire internal collection of objects? `ArrayCollection` implements [`\ArrayAccess`](http://php.net/manual/en/class.arrayaccess.php), so you can access internal elements like a normal array:

```php
foreach ($serverList as $server) {
   printf("%s\n", $server->id);
}

$firstServerId = $serverList[0]->id;
```

**Comment by jamiehannaford** [comment]
@joubertredrat I'm going to go ahead and close this, since I think your questions are answered. If you need any more help please comment here and I'll reopen the thread

**Comment by calofiremil** [comment]
I have a similar problem, see below, when trying accessing server metadata

> "SDK tried to get from wrong http://mydomain instead of https://mydomain "

So i can't use 

`foreach ($serverList as $server) {
   printf("%s\n", $server->id);
}
`

to list my servers. I'm getting 

`[curl] 52: Empty reply from server [url] http://mydomain:8774/v2/03932c400ac947eb8a60f17fda9a28b9/servers/82c562dc-7cdc-4092-85b4-aeca6d9b3b4a/metadata
`

My computeService `$service = $client->computeService('nova', 'regionOne', 'publicURL');`

**Comment by jamiehannaford** [comment]
@calofiremil This turned out to be a problem with @joubertredrat's OpenStack API. @joubertredrat, do you remember how you fixed it?

**Comment by calofiremil** [comment]
Thank you for replying so quickly! 
I made a request `$service->serverList()` and obtain a detailed list of servers of a tenant. 
Is there another way of extracting that server list from the `PaginatedIterator` ? 
I'm a bit confused, why during server list iteration a new request, for metadata, for each server is made if i already have all the details i need?

**Comment by jamiehannaford** [comment]
@calofiremil Because a decision was made early on in the SDK to request the server metadata every time a new Server object is instantiated. I think it was a very bad idea, but we have to keep it in to maintain backwards compatibility. You can suppress the errors:

Is it possible for you to comment out this line? https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Compute/Resource/Server.php#L248

**Comment by calofiremil** [comment]
That resolve my problem, but unfortunately I'm using Symfony framework and this modification inside `vendor/rackspace/php-opencloud/lib/OpenCloud/Compute/Resource/Server.php` will not be propagated when deploying.

**Comment by calofiremil** [comment]
Well, i was forced to overwrite the `OpenCloud/Common/Collection/PaginatedIterator.php` and add a new method `getElements()` to solve this particular case
