### ISSUE TITLE
need instructions for installation without composer

### ISSUE THREAD

**Issue by sneakyimp** [rackspace/php-opencloud#634]
Some of us who would like to access the Rackspace cloud would like to use php-opencloud without installing composer for security reasons. You should have instructions on how to install this without using Composer.

FYI:
https://github.com/composer/composer/issues/1074

**Comment by jamiehannaford** [comment]
@sneakyimp The issue you referenced lists lack of package signing as the key security flaw (which I totally agree with). But I'm not sure manually installing the dependencies yourself would overcome this problem, since Github (nor any of the project owners to my knowledge) currently support this. Sure you could download via HTTPS, but that's only one part of the problem.

If you are determined to work around Composer, you would need to download all of [the dependencies](https://github.com/rackspace/php-opencloud/blob/working/composer.json#L20-L23) directly, verify them (not sure how you'd do this?), create your own PHP autoloader, and manually upgrade codebases every so often. 

Despite the lack of package signing and dodgy TLS support, Composer still remains the de facto standard for package management in the PHP community. If users do not want to use the default package manager, they're more than welcome to install things according to their own preferences, but I don't think that's within the remit of this project or its documentation.

**Comment by jamiehannaford** [comment]
The only option I can see would be to:

1. generate a gpg keypair for the project
2. upload the public key to some kind of public server
3. before a release, bundle the SDK up into a phar or zip file
4. sign the file with the gpg private key
5. re-upload the signed file to Github for user downloading

There are two problems here though: 

- which server to upload the public key to (is there a standard?)
- how would the package maintainers corroborate the integrity of the dependencies before cutting a release? I don't think this is really possible until there's widespread package signing.

**Comment by sneakyimp** [comment]
>Despite the lack of package signing and dodgy TLS support, Composer still remains the de facto standard for package management in the PHP community. If users do not want to use the default package manager, they're more than welcome to install things according to their own preferences, but I don't think that's within the remit of this project or its documentation.

The implication of this statement is that php-opencloud's dependencies have also not been vetted either, which is regrettable, especially given the power of cloud computing and the sensitivity of one's rackspace credentials.

Sadly, the convenience of composer -- whether it's defacto or not -- comes at the expensive of security.

Perhaps you could at least document the minimum dependencies required for a production environment? It would appear from your link that they are as follows:
```
        "php" : ">=5.4",
        "guzzle/guzzle" : "~3.8",
        "psr/log": "~1.0",
        "mikemccabe/json-patch-php": "~0.1"
```
Another question: Why php 5.4? Is there something missing in php 5.3 (still in use by Ubuntu 12.04.5 whose end of life is not until April 2017).

**Comment by jamiehannaford** [comment]
@sneakyimp They have been vetted, and deemed suitable for our SDK. The minimum dependencies are the ones I linked to: PHP 5.4, Guzzle ~3, PSR Log ~1, JSON Patch ~0.

PHP 5.3 is officially deprecated and no longer even receives security updates. It's been EOL for well over a year now. We also needed 5.4 for a dependent library. The v2 library will use 5.6 as a minimum.

**Comment by sneakyimp** [comment]
Sometimes deprecated software remains in use. E.g., guzzle/guzzle (one of your own dependencies) is now deprecated. Ubuntu 12.04 does in fact supply security patches to Ubuntu 5.3 -- its latest is 5.3.10-1ubuntu3.20. Which library do you need in 5.4?

As for jumping straight to 5.6 for V2 -- any reason for that? EOL for PHP 5.5 hasn't even been announced yet.

**Comment by jamiehannaford** [comment]
If you need support for 5.3, you can use any version before v1.13. Composer can do this for you by pinning versions on your behalf.

5.6 is the current stable version.

**Comment by sneakyimp** [comment]
According to this chart, dated today, php 5.6 represents about 3% of all current php installations:
http://w3techs.com/technologies/details/pl-php/5/all

PHP 5.3.29 is also what's running on our numerous CentOS 6.7 servers at *rackspace*.

**Comment by jamiehannaford** [comment]
@sneakyimp Are you referring to previously deployed servers or brand-new ones? There's a chance that those servers were deployed when 5.3 was not deprecated. My opinion is that 5.3 should not be offered as a default for yum or apt downloads on newer servers. The last time I tried, though, 5.4 seems to have been the default.

If you need help upgrading to a supported version of PHP, I recommend reaching out to our Linux support team via a Control Panel ticket, and depending on your SLA, we will be able to help reconfigure the server environment.

**Comment by sneakyimp** [comment]
In answer to the question "When will php 5.6 be in the official repos?"
" I Just got an email back from Marc Deslauriers (security engineer at Canonical, so somebody who would know) and the answer is: Probably never. Unless something goes catastrophically wrong with 5.5, it'll have security patches backported for the lifespan of 14.04."
From here: http://askubuntu.com/questions/527533/when-will-php-5-6-be-in-the-official-canonical-repos

**Comment by sneakyimp** [comment]
Also, just called rackspace to found out the LATEST distro of Ubuntu/Debian they offer and the answer is:
Rackspace linux:
* Debian 8 - php version 5.5.9
* Ubuntu 14.04 - php version 5.5.9

**Comment by jamiehannaford** [comment]
Okay, thanks for the info. For users on 14.04 or below, they can carry on using the v1 library without a problem. For users able to upgrade (i.e. those on Ubuntu 15.04+ or any other platform), they can shift to v2 and use the [new library](https://github.com/php-opencloud/openstack). We desperately need to move on, and although legacy support is definitely an important consideration, newer major versions of the SDK should not be beholden to old distros.

**Comment by sneakyimp** [comment]
I can appreciate a desire to move forward (obviously upgrading guzzle is something that needs doing). Ubuntu 15+ is not an LTS distro so I think it's unlikely to be used much for server applications. I'm curious what features of 5.6 are so important. I've written PHP applications twelve years ago that still run.

Also, it would be *really* nice if you had instructions on how to install php-opencloud without using composer -- especially considering your installation instructions rely on a now-deprecated dependency. I'm very disappointed that you have closed this issue.

**Comment by jamiehannaford** [comment]
@sneakyimp Apologies, but we're not in a position to advocate anything other than Composer right now - there are no feasible alternatives.
