### ISSUE TITLE
ObjectStore list over 10000 objects

### ISSUE THREAD

**Issue by Bubazineti** [rackspace/php-opencloud#636]
Following the example at http://php-opencloud.readthedocs.org/en/latest/services/object-store/objects.html#list-over-10-000-objects

I'm having a hard time getting greater than 10000 objects from a container. 
The example utilising a marker doesn't seem to work when a PaginatedIterator returned.

I thought something along the lines of the following would work but it caps out at 10000.

$options = array(
	'prefix' => 'assets/swf',
        'limit.total' => 15000
);
// @ OpenCloud\Common\Collection\PaginatedIterator
$iterator  = $container->objectList($options);
$count = 0;
while($iterator->valid()) {
	$object = $iterator->current();
	$count ++;
	$iterator->next();
}

**Comment by jamiehannaford** [comment]
@Bubazineti Are you using OpenStack or Rackspace? The first has a [maximum of 10,000 per HTTP call](http://developer.openstack.org/api-ref-objectstorage-v1.html). What happens when you use the sample in the link you posted?

**Comment by Bubazineti** [comment]
Hi Jamie,
I'm using Rackspace (rackspace/php-opencloud). This is the example code i'm using:

```php
$container = ObjectStore::getInstance()->getContainer('project.cdn');

$containerObjects = array();
$marker = '';

while ($marker !== null) {
    $params = array(
        'marker' => $marker,
        'prefix' => 'assets/swf'
    );

    $objects = $container->objectList($params);
    $total = $objects->count();
    Cli::trace($total);
    $count = 0;

    if ($total == 0) {
        break;
    }

    foreach ($objects as $object) {
        /** @var $object OpenCloud\ObjectStore\Resource\DataObject **/
        $containerObjects[] = $object->getName();
        $count++;
        $marker = ($count == $total) ? $object->getName() : null;
	Cli::trace($marker);
    }
}

Cli::trace($count);
```

Cli is just a command line utility class.
The total traced is 100 and is only traced once.
The marker is always an empty string and the final count is 10000. There are c.15000 objects with that prefix.

I see that if you create a PaginatedIterator directly you can specify a larger total.

Cheers,
Luke.

**Comment by jamiehannaford** [comment]
@Bubazineti Yeah, I think you might need to use the PaginatedIterator directly for more advanced usage:

```php
$options = $container->makeResourceIteratorOptions('Object');
$options['baseUrl'] = $container->getUrl([
  'marker' => $marker,
  'prefix' => 'assets/swf'
  'format' => 'json',
]);

$iterator = PaginatedIterator::factory($container, $options);

foreach ($iterator as $object) {

}
```

**Comment by Bubazineti** [comment]
@jamiehannaford So i've been able to retrieve all the objects.

The first example grabs up to 20000 objects

```php
$service = $client->objectStoreService(null, 'DFW', 'publicURL');
$container = $service->getContainer('project.cdn');
$count = 0;
$iterator = PaginatedIterator::factory($container, array(
	'resourceClass' => 'dataObject',
	'baseUrl' => $container->getUrl(null, array(
		'prefix' => 'assets/swf/',
		'format' => 'json'
	)),
	'limit.total' => 20000
));
foreach ($iterator as $object) {
	//print_r($object->getName());
	$count ++;
}
print_r($count);
```

The second does the same in chunks. I'm sure there's a method to get the total number of objects in all pages of the iterator. objectcount() returns the objects in a page i.e. 100

```php
$count = 0;
$marker = '';
$limit = 500;
while ($marker !== null) {
	$iterator = PaginatedIterator::factory($container, array(
		'resourceClass' => 'dataObject',
		'baseUrl' => $container->getUrl(null, array(
			'prefix' => 'assets/swf/',
			'format' => 'json',
			'marker' => $marker
		)),
		'limit.total' => $limit
	));
	$iteratorCount = 0;
	print_r($marker);
	foreach ($iterator as $object) {
		$iteratorCount ++;
		//$marker = $object->getName();
	}
	$count += $iteratorCount;
	$marker = ($iteratorCount < $limit) ? null : $object->getName();
}
print_r($count);
```

Thanks,
Luke.
