### ISSUE TITLE
How can I confirm create Object successful on swift?

### ISSUE THREAD

**Issue by kebenxiaoming** [rackspace/php-opencloud#640]
I use opencloud to create object on swift,like this:

$container->uploadObject($filename,$filestream);

this method return like this:

return $this->dataObject()
            ->populateFromResponse($response)
            ->setName($name)
            ->setContent($entityBody);

And the swift document show me this(http://developer.openstack.org/api-ref-objectstorage-v1.html):

The 201 Created status code indicates a successful write.

If the request times out, the operation returns the 408 Request Timeout error code.

The 411 Length Required error code indicates a missing Transfer-Encoding or Content-Length request header.

If the MD5 checksum of the data that is written to the object store does not match the optional ETag value, the operation returns the 422 Unprocessable Entity error code.

 So how can I confirm create successful with this object?

wait for response and thx.

**Comment by jamiehannaford** [comment]
@kebenxiaoming if you just some form of boolean value, you can use `objectExists`:

```php
if ($container->objectExists($name)) {

}
```

if you want to check the new object's content matches your local version, you will need to download it:

```php
$newObject = $container->getObject($name);
if ($newObject->getContent() != $entityBody) {

}
```

**Comment by kebenxiaoming** [comment]
@jamiehannaford 
OK,thanks a lot!
