### ISSUE TITLE
Add support for  interfaces router

### ISSUE THREAD

**Issue by haongovan** [rackspace/php-opencloud#647]
Can we please get support for add interfaces router in create ports or new function add interfaces router ? 

$port = $networkService->createPort(array(
			'name' => 'route',
			'networkId' => '32552ff6-fb4d-4bb0-9282-83d947da81a8',
			'deviceOwner' => 'network:router_interface',
			'fixedIps' => array(array('subnetId' => '10e9922a-5c51-40d3-84f3-71c88d8f1a20', 'ipAddress' => '10.1.1.253')),
			'deviceId' => 'ID router'
	));
check  Interfaces router,  Status DOWN

**Comment by jamiehannaford** [comment]
@haongovan Are you using OpenStack or Rackspace? 

No new functionality will be added to this SDK. We will be releasing the [v2 SDK](https://github.com/php-opencloud/openstack) for OpenStack soon, and the Rackspace one a few months after.

**Comment by haongovan** [comment]
Thanks Jamie response
I am using Openstack. I hope functionality soon update.

**Comment by jamiehannaford** [comment]
This is now offered in https://github.com/php-opencloud/openstack
