### ISSUE TITLE
Public Temp URL for file download broken when URL type internal

### ISSUE THREAD

**Issue by matt-in-a-hat** [rackspace/php-opencloud#648]
It looks like this was attempted to be fixed here https://github.com/rackspace/php-opencloud/issues/594 however it seems that this always results in `401 Unauthorized: Temp URL invalid` because the URL doesn't have the container and file name in it.

As far as I can see if you use `$forcePublicUrl` below then it misses out on the extra things that `DataObject::getUrl()` adds to the URL path, namely the container and file name.
`$url = ($forcePublicUrl === true) ? $this->getService()->getEndpoint()->getPublicUrl() : $this->getUrl();`
(see https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/ObjectStore/Resource/DataObject.php#L484)

My work around for now is to ensure I instantiate the object store service with `publicURL` when wanting to generate temporary URLs for download.

**Comment by jamiehannaford** [comment]
@matt-in-a-hat Good catch. I imagine the solution would be something like:

```php
$baseUrl = $this->getUrl();

$url = ($forcePublicUrl === true) 
   ? $baseUrl->combine($this->getService()->getEndpoint()->getPublicUrl()) 
   : $baseUrl;
```

Does this work for you?

**Comment by matt-in-a-hat** [comment]
Works for me with the combine swapped around.
```php
$this->getService()->getEndpoint()->getPublicUrl()->combine($baseUrl)
```
