### ISSUE TITLE
uploadDirectory() with many files causing seg fault (PHP 5.3.29)

### ISSUE THREAD

**Issue by ncharlot** [rackspace/php-opencloud#654]
Hello,

We're trying to synchronize our current filers (25 To of images) to an OpenStack Object Store (OVH Object Storage).

Images are stored in their owner dir and we have about 22 000 owners.
So it looks like:

    owner1:
    |_ subdir1
       |_ image1.jpg
       |_ imageN
       …
    |_ subdirN
    ...
    owner2:
    |_ subdir1
    ownerN
    ...

To ease sync process, 1 owner dir = 1 container and we're using `uploadDirectory()` on each one.

After 8 owner dirs synchronized, we got a "segmentation fault"...
Owner #8 dir has a weight of 3,7 GB with 2.477 images.

**Comment by jamiehannaford** [comment]
Unfortunately we do not support anything below 5.4. I suspect it is a legacy performance issue or something to do with memory allocation.
