### ISSUE TITLE
Percent Signs in Object Names causes 400 error

### ISSUE THREAD

**Issue by PatrickRose** [rackspace/php-opencloud#656]
Some files that I've been trying to upload as part of a migration to Swift have been returning 400 errors, and I couldn't work out why, until I spotted that the file names had a percent in them which doesn't look like it gets escaped. I don't think Guzzle does any urlencoding, so it looks like OpenCloud needs to do that.

I think it's sufficient to do `preg_replace('/\%(?!\d{2})/', '%25', $objectName)` when requesting an object. Putting `[]{}` in my object name was handled without errors.

**Comment by PatrickRose** [comment]
Of course, there's lots of places where this needs handling. Currently I've found:
- `Container::uploadObject()`
- `DataObject::refresh()`
- `Container::objectExists()`
- `Container::uploadObject()`
- `TransferPart::createRequest()`

Maybe it'd be better to override the create request and catch it there?

**Comment by jamiehannaford** [comment]
No new functionality is being added to this version of the SDK. The [newer version](https://github.com/php-opencloud/openstack) is recommended for connecting to OpenStack clouds. I'd be happy to look into this issue if it affects the newer codebase.

If you are not in a position to migrate, a short-term fix would be to urlencode the filename yourself before uploading and after retrieving.

**Comment by PatrickRose** [comment]
I've currently overridden guzzle's RequestFactory to urlencode the full path since that meant I only had to do it in one place.

**Comment by PatrickRose** [comment]
It's actually explicitly mentioned in the docs that [urlencoding should be done before it hits the SDK](http://docs.php-opencloud.com/en/latest/services/object-store/objects.html#create-an-object) - I'll close this.
