### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by Hypoaristerolactotherapist** [rackspace/php-opencloud#669]
Hi,

when you ship this (great, by the way) project to Packagist, could you remove the .git directory. It messes up my git installation by making your code as a submodule of my code that I have many pains to push.

Each time I update I need to manually remove your .git directory, add all your files to my change list and then I can commit.

Thanks

**Comment by PatrickRose** [comment]
I'm not getting this issue. The general suggestion is to not include your vendor directory in your git repo by adding it to your .gitignore
