### ISSUE TITLE
Fatal error while uploading image to Rackspace CDN

### ISSUE THREAD

**Issue by z013j4k** [rackspace/php-opencloud#673]
Hi, I'm facing this intermittent issue while trying to uploading image to Rackspace throwing error like:

> Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: Unknown SSL protocol error in connection to identity.api.rackspacecloud.com:443 [url] https://identity.api.rackspacecloud.com/v2.0/tokens' in /Applications/XAMPP/xamppfiles/htdocs/CG-Configurator/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/CG-Configurator/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #1 /Applications/XAMPP/xamppfiles/htdocs/Projectname/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #2 /Applications/XAMPP/xamppfiles/htdocs/Project Name/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\Cu in /Applications/XAMPP/xamppfiles/htdocs/CG-Configurator/api/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 359

I'm using PHP latest SDK downloaded using composer. I'm new to Rackspace CDN. Kindly help me in resolving this issue

**Comment by jamiehannaford** [comment]
@z013j4k How regularly does this happen? Is it an intermittent problem, or does it occur every time you authenticate?

**Comment by z013j4k** [comment]
That's an intermittent issue. From last an hour it's working fine again. So not able to figure out what is causing this.

Thanks for your prompt reply though

**Comment by jamiehannaford** [comment]
You can use the [exponential backoff](https://gist.github.com/jamiehannaford/8432889) plugin to retry failed connections of specific cURL error codes. This will prevent the intermittent errors bubbling up.

If this does not solve the problem, I recommend opening a support ticket in the control panel and pasting the error. They will be able to crawl the API logs and contact the identity team on your behalf.

**Comment by z013j4k** [comment]
Sure, I've added backoff plugin code to my project. Let me watch if this occurs again. As you said if this doesn't solve this issue then probably I'd try to open a ticket.

**Comment by jamiehannaford** [comment]
@z013j4k Okay, sounds good. I'm going to go ahead and close this issue, since it seems you have a handle on things. If you need additional help please comment here and I'll reopen.

**Comment by z013j4k** [comment]
Hi, It seems we have to reopen this issue as again Unfortunately I started seeing same error thrown on me while trying to upload file despite of backoff function included to my code.

**Comment by jamiehannaford** [comment]
@z013j4k Can you paste the backoff code you're using?

**Comment by z013j4k** [comment]
Here is my code:
private $client;
  private $objectStoreService;
  private $container;

  function __construct()
  {
    $this->container = false;
    $this->client = new Rackspace(Rackspace::US_IDENTITY_ENDPOINT, array(
        'username' => USER_NAME,
        'apiKey'   => API_KEY
    ));

```
/**
* Use the exponential backoff plugin to retry failed connections of specific
* cURL error codes. This will prevent the intermittent errors bubbling up.
* For more info go to: https://gist.github.com/jamiehannaford
*/
$this->backoff();

$this->objectStoreService = $this->client->objectStoreService(null, LOCATION);
$this->container = $this->getCloudContainer();
```

  }

  private function backoff(){
    try{
      $maxRetries = 5;
      $httpCodes = array(503);
      $curlCodes = array(50);
      $backoff = BackoffPlugin::getExponentialBackoff($maxRetries, $httpCodes, $curlCodes);

```
  $this->client->addSubscriber($backoff);
}
catch(Exception $e){
  $this->response($this->json(array("Error in back off plugin" => $e->getMessage())), 503);
}
```

  }

**Comment by jamiehannaford** [comment]
the cURL code you're receiving is 35, but in your code you're only telling the client to retry code 50. You need to add 35 to $curlCodes

**Comment by z013j4k** [comment]
Sorry about that, I thought its standard code to be added. Though I've changed it now, let's hope it works fine now :)

Not sure but a thought if you would like to add some more comments to add_backoff.php about these variables.

Thanks a lot for on time help.
