### ISSUE TITLE
Uploading directly to CloudFiles

### ISSUE THREAD

**Issue by jjmontgo** [rackspace/php-opencloud#675]
Hello:

I'm sorry this isn't really an issue.  I'm not sure where to post the question.  If you could direct me somewhere else, that would be very helpful.

I'd like to use the following method for posting files directly to CloudFiles:

https://developer.rackspace.com/docs/cloud-files/v1/developer-guide/#formpost

I'm wondering if there is any reference for how to do this using the PHP SDK?  I looked through the docs and couldn't find anything (except uploading files already on the server).

Any help would be appreciated.

**Comment by ghost** [comment]
http://docs.php-opencloud.com/en/latest/

**Comment by jamiehannaford** [comment]
@jjmontgo Instructions for creating temporary URLs are here: http://docs.php-opencloud.com/en/latest/services/object-store/access.html. If you need any more information, please comment on this thread and I'll reopen this issue.
