### ISSUE TITLE
Fetch specific object list

### ISSUE THREAD

**Issue by dmitrirussu** [rackspace/php-opencloud#677]
Hi, can I fetch a specific list of objects, to setup on getter method list of file names which I need to fetch, for example to have a method which will ->getObjectsBy(array('file.xx1', 'file.xx2', 'file.xx3'))?

**Comment by jamiehannaford** [comment]
No. You can provide prefixes though: https://github.com/rackspace/php-opencloud/blob/working/samples/ObjectStore/list-objects-with-prefix.php

**Comment by dmitrirussu** [comment]
but can be developed some thing, because I see you have some thing on delete Action as delete batch by specific file names. can you implement a method for fetch by specific names?

**Comment by dmitrirussu** [comment]
I want to avoid multiple requests, fetch by prefix does not help so much is to abstract for me

**Comment by jamiehannaford** [comment]
There is no way to do this in a single request, the closest thing you have to that performance is using `listObjects` with a prefix.

I don't see the value in a `getObjects` method. Why can't you run:

``` php
$names = ['foo1', 'foo2'];
foreach ($names as $name) {
   $files[$name] = $container->getObject($name);
}
```
