### ISSUE TITLE
vendor/rackspace is not created by composer

### ISSUE THREAD

**Issue by hrazack** [rackspace/php-opencloud#678]
Ok, so really simple: I downloaded the whole zip archive, unzipped it in a folder, and ran "composer require rackspace/php-opencloud:dev-master"

All goes well, no errors, the "vendor" folder is created and populated with quite a lot of folders.... except it doesn't create any "vendor/rackspace" folder. So, it fetches everything except the opencloud.php stuff.

I've tried deleted the "vendor" folder and running "composer update", and again it works very well but doesn't create "vendor/rackspace".

Any suggestions? Thanks a lot for your assistance!

**Comment by PatrickRose** [comment]
This sounds like a composer bug possibly, but that sounds unlikely. I'd try deleting your composer.lock file and the vendor directory and running `composer install` again.

Might be worth dumping the output of doing that and your composer.json in this issue.

**Comment by hrazack** [comment]
Thanks a lot for the reply and suggestion, that's much appreciated. It seems to have produced the same effect as before. It all runs smoothly, but no vendor/rackspace folder in sight.

Here is the content of composer.json:

> {

```
"name": "rackspace/php-opencloud",
"description": "PHP SDK for Rackspace/OpenStack APIs",
"keywords": ["rackspace", "openstack", "opencloud", "swift", "nova"],
"type": "library",
"license": "Apache-2.0",
"authors": [
    {
        "name": "Jamie Hannaford",
        "email": "jamie.hannaford@rackspace.com",
        "homepage" : "https://github.com/jamiehannaford"
    }
],
"autoload": {
    "psr-0": {
        "OpenCloud": ["lib/"]
    }
},
"autoload-dev": {
    "psr-0": {
        "OpenCloud": ["tests/"]
    }
},
"require": {
    "php" : ">=5.4",
    "guzzle/guzzle" : "~3.8",
    "psr/log": "~1.0",
    "mikemccabe/json-patch-php": "~0.1",
    "rackspace/php-opencloud": "dev-master"
},
"require-dev" : {
    "phpunit/phpunit": "4.3.*",
    "phpspec/prophecy": "~1.4",
    "satooshi/php-coveralls": "0.6.*@dev",
    "jakub-onderka/php-parallel-lint": "0.*",
    "fabpot/php-cs-fixer": "1.0.*@dev",
    "apigen/apigen": "~4.0"
},
"extra": {
    "branch-alias": {
        "dev-working": "1.16-dev"
    }
}
```

}

And here is the output of `composer install`:

Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing mikemccabe/json-patch-php (0.1.0)
  Loading from cache
- Installing sebastian/diff (1.4.1)
  Loading from cache
- Installing symfony/stopwatch (v2.8.8)
  Loading from cache
- Installing symfony/process (v2.8.8)
  Loading from cache
- Installing symfony/finder (v2.8.8)
  Loading from cache
- Installing symfony/filesystem (v2.8.8)
  Loading from cache
- Installing symfony/event-dispatcher (v2.8.8)
  Loading from cache
- Installing symfony/polyfill-mbstring (v1.2.0)
  Loading from cache
- Installing symfony/console (v2.8.8)
  Loading from cache
- Installing fabpot/php-cs-fixer (v1.0)
  Loading from cache
- Installing psr/log (1.0.0)
  Loading from cache
- Installing guzzle/guzzle (v3.9.3)
  Loading from cache
- Installing symfony/config (v3.1.2)
  Loading from cache
- Installing symfony/yaml (v2.8.8)
  Loading from cache
- Installing satooshi/php-coveralls (v0.6.1)
  Loading from cache
- Installing jakub-onderka/php-parallel-lint (v0.9.2)
  Loading from cache
- Installing latte/latte (v2.3.4)
  Loading from cache
- Installing apigen/theme-bootstrap (v1.1.3)
  Loading from cache
- Installing apigen/theme-default (v1.0.2)
  Loading from cache
- Installing herrera-io/version (1.1.1)
  Loading from cache
- Installing seld/jsonlint (1.4.0)
  Loading from cache
- Installing justinrainbow/json-schema (1.6.1)
  Loading from cache
- Installing herrera-io/json (1.0.3)
  Loading from cache
- Installing herrera-io/phar-update (2.0.0)
  Loading from cache
- Installing symfony/options-resolver (v2.6.13)
  Loading from cache
- Installing nette/utils (v2.4.0)
  Loading from cache
- Installing nette/php-generator (v2.4.0)
  Loading from cache
- Installing nette/neon (v2.4.0)
  Loading from cache
- Installing nette/di (v2.4.1)
  Loading from cache
- Installing kdyby/events (v2.4.1)
  Loading from cache
- Installing nette/finder (v2.4.0)
  Loading from cache
- Installing nette/caching (v2.5.0)
  Loading from cache
- Installing nette/reflection (v2.4.0)
  Loading from cache
- Installing tracy/tracy (v2.4.1)
  Loading from cache
- Installing nette/safe-stream (v2.3.2)
  Loading from cache
- Installing nette/robot-loader (v2.4.0)
  Loading from cache
- Installing nette/mail (v2.4.0)
  Loading from cache
- Installing nette/http (v2.4.0)
  Loading from cache
- Installing nette/component-model (v2.3.0)
  Loading from cache
- Installing nette/bootstrap (v2.4.1)
  Loading from cache
- Installing nette/application (v2.4.0)
  Loading from cache
- Installing michelf/php-markdown (1.6.0)
  Loading from cache
- Installing andrewsville/php-token-reflection (1.4.0)
  Loading from cache
- Installing kukulich/fshl (2.1.0)
  Loading from cache
- Installing apigen/apigen (v4.1.2)
  Loading from cache
- Installing sebastian/version (1.0.6)
  Loading from cache
- Installing sebastian/recursion-context (1.0.2)
  Loading from cache
- Installing sebastian/exporter (1.2.2)
  Loading from cache
- Installing sebastian/environment (1.3.7)
  Loading from cache
- Installing sebastian/comparator (1.2.0)
  Loading from cache
- Installing doctrine/instantiator (1.0.5)
  Loading from cache
- Installing phpunit/php-text-template (1.2.1)
  Loading from cache
- Installing phpunit/phpunit-mock-objects (2.3.8)
  Loading from cache
- Installing phpunit/php-timer (1.0.8)
  Loading from cache
- Installing phpunit/php-file-iterator (1.3.4)
  Loading from cache
- Installing phpunit/php-token-stream (1.4.8)
  Loading from cache
- Installing phpunit/php-code-coverage (2.2.4)
  Loading from cache
- Installing phpunit/phpunit (4.3.5)
  Loading from cache
- Installing webmozart/assert (1.0.2)
  Loading from cache
- Installing phpdocumentor/reflection-common (1.0)
  Loading from cache
- Installing phpdocumentor/type-resolver (0.2)
  Loading from cache
- Installing phpdocumentor/reflection-docblock (3.1.0)
  Loading from cache
- Installing phpspec/prophecy (v1.6.1)
  Loading from cache

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
jakub-onderka/php-parallel-lint suggests installing jakub-onderka/php-console-highlighter (Highlight syntax in code snippet)
nette/utils suggests installing ext-intl (for script transliteration in Strings::webalize() and toAscii())
nette/application suggests installing nette/forms (Allows to use Nette\Application\UI\Form)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files`

**Comment by PatrickRose** [comment]
Ahhhh. You don't need to download the zip for this package to use it in your project. You should just run `composer require rackspace/php-opencloud` inside your project's directory.

I'm surprised composer doesn't complain that the dependencies can't be resolved since you're requiring `rackspace/php-opencloud` inside `rackspace/php-opencloud`.

**Comment by hrazack** [comment]
Aaah, yes, well ok, that was a bit dumb.... :-) Thanks a lot for the help, Patrick, that's much appreciated!
All working perfectly now.
