### ISSUE TITLE
GetObjects failure for file that exists

### ISSUE THREAD

**Issue by brettnem** [rackspace/php-opencloud#687]
Hello
I've been using the cloud files API for quite some time without issue. However, lately (last few months) I'm getting intermittent errors. When calling my $container->getObject($filename) I'm getting an exception. I've manually checked for the file and it really really is there. The container has about 9G of 1M-15M files, so there's a lot in it. 

Here's the exception I'm getting. I've removed some of the hashes, because I'm not sure what is "sensitive" here.

exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 23: Failed writing body (0 != 16384) [url] https://storage101.ord1.clouddrive.com/v1/MossoCloudFS_UUID_REMOVED/account_742/1470325911.6382.wav' in /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338
Stack trace:
#0 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(105): Guzzle\Http\Curl\CurlMulti->perform()
#5 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(91): Guzzle\Http\Curl\CurlMulti->send()
#6 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Client.php(282): Guzzle\Http\Curl\CurlMultiProxy->send()
#7 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\Request))
#8 /usr/local/repo/salesforce/setup/SFDC/RSRecordings/vendor/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Resource/Container.php(330): Guzzle\Http\Message\Request->send()
#9 /usr/local/repo/salesforce/setup/SFDC/GetRecordingCLI.php(79): OpenCloud\ObjectStore\Resource\Container->getObject('1470325911.6382...')
#10 /usr/local/repo/salesforce/setup/SFDC/GetRecordingCLI.php(32): getRecording(Object(OpenCloud\ObjectStore\Service), '1470325911.6382', 1)
#11 {main}<br>

Any idea? I can reproduce almost every time, and like I said, if I go thru the web interface, I can see the file just fine. 

-Brett

**Comment by brettnem** [comment]
Hello, any update please? Thanks!

**Comment by jamiehannaford** [comment]
@brettnem All I can suggest is to implement a retry handler that retries specific cURL/HTTP failures. To implement you will need to install the backoff plugin:

``` bash
$ composer require guzzle/guzzle
```

And then add this to your code:

``` php
use Guzzle\Plugin\Backoff\BackoffPlugin;
use OpenCloud\Rackspace;

$client = new Rackspace(Rackspace::US_IDENTITY_ENDPOINT, array(
  'username' => 'foo',
  'apiKey'   => 'bar'
));

$maxRetries = 5;
$httpCodes = array();
$curlCodes = array(23);
$backoff = BackoffPlugin::getExponentialBackoff($maxRetries, $httpCodes, $curlCodes);
$client->addSubscriber($backoff);
```

That should retry all failed connections due to `[curl] 23` errors. This seems like a problem with either the API or your server environment, so I don't feel there's much an SDK can do here apart from retry things the best it can.
