### ISSUE TITLE
Cloud files integration with videjs player.

### ISSUE THREAD

**Issue by cyberformed** [rackspace/php-opencloud#688]
Can be cloud files api be integrated with videojs player. I just want have a video hosting website. I want to the video should played using the videojs plugin with HTML5 video tag. can it be possible?

**Comment by jamiehannaford** [comment]
@cyberformed You can use the [`$object->getPublicUrl('Streaming')`](https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/ObjectStore/Resource/DataObject.php#L523) method to retrieve the streaming URL, and then use it in the HTML tag.

**Comment by cyberformed** [comment]
Thanks for  your reply. one thing to ask can it be encrypted and can be only accessible for once. if someone has copied that link and opened somewhere else, can it be blocked using cloud files.

**Comment by jamiehannaford** [comment]
@cyberformed No we don't offer that.
