### ISSUE TITLE
Curl errors when using claimMessages

### ISSUE THREAD

**Issue by ks217** [rackspace/php-opencloud#690]
I am running a consumer using claimMessages function. It calls claimMessages (with a limit of 10) to "my_queue", processes the messages if any, and then sleeps for 60 seconds, and then calls again.

Today while running it, after approx 2 hours, it threw this curl error and the script stopped : 
`[curl] 52 : Empty reply from server [url] https://iad.queues.api.rackspacecloud.com/v1/xxxxxx/queues/my_queue/claims?limit=10%`

And then when we ran it again, after sometime it threw this error:
`[curl] 35: Server aborted the SSL handshake [url] https://iad.queues.api.rackspacecloud.com/v1/xxxxxx/queues/my_queue/claims?limit=10%`
During this second time no messages were published, hence the consumer was calling claimMessages every minute and doing nothing else.

Note: "xxxxxx" and "my_queue" are used to hide actual ids and queue name.

Any idea when / why this happens while using the API/SDK ? Thanks in advance.

**Comment by ks217** [comment]
Can someone please help me with this?
Still facing this issue intermittently.

**Comment by jamiehannaford** [comment]
@kartik21790 For intermittent cURL errors, you will need to use a retry handler to retry failed connections:

https://gist.github.com/jamiehannaford/8432889

**Comment by ks217** [comment]
thanks a lot @jamiehannaford :)
This Guzzle Backoff Plugin will be very helpful for this case.
I have switched to a cron instead of a continuous running process after which curl errors never occurred, hence haven't given it a try.

Closing this issue as of now.
