### ISSUE TITLE
v2 release?

### ISSUE THREAD

**Issue by kynx** [rackspace/php-opencloud#691]
Don't mean to nag, but any idea on how the v2 stuff is progressing? From what I can tell it's some months since the v1 deprecation warning went up...

**Comment by jamiehannaford** [comment]
@kynx Unfortunately I've been brought onto another internal project, so all SDK development is on hiatus for the foreseeable future. I will try to switch back to this project when I can but can't make any promises right now. All the work is on the `v2` branch, so feel free to check out if you would like.

**Comment by kynx** [comment]
Thanks for the update. I'll give it a try :)

**Comment by kynx** [comment]
@jamiehannaford I've tried to get the tests running on the v2 branch, but there are a number of changes required before I can even get that far :(

* The OpenCloud namespace is now OpenStack
* Most of the models should now extend OperatorResource instead of AbstractResource
* A number of the Api methods called in the Models have been renamed. 

I can do a PR with progress to date, but it'll be big. Would you prefer it split out by class of problem (like above), or should I do a WIP until (if!) I get to the point of tests passing?

**Comment by jamiehannaford** [comment]
Hi @kynx, unfortunately I no longer maintain this repo (I've been brought onto another project). We're still looking for a replacement. I would advise you break up your PR into smaller components so that the new maintainer has an easy job in merging them.

**Comment by kynx** [comment]
Yeah that's too bad @jamiehannaford. I'll do that if I can find the time.
