### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by sneakyimp** [rackspace/php-opencloud#699]
The [README](https://github.com/rackspace/php-opencloud/blob/working/README.md) for this project is incorrect. It says:

>OpenStack users are recommended to use https://github.com/php-opencloud/openstack, which is the latest supported version of the SDK. This codebase which you are now looking at will enter end-of-life soon. For Rackspace Cloud users, a v2 is actively being worked on.

The Rackspace twitter acocunt has [stated](https://twitter.com/Rackspace/status/841428796410609664) that there is no ETA for php-opencloud V2.

No one has touched this repo since July 2016. No one has touched the [v2 version](https://github.com/rackspace/php-opencloud/tree/v2) since *March* 2016.

Can we PLEASE get some clarity about this SDK? I'm deathly afraid of building any projects using it because it appears to have been completely abandoned. 

In any case, the README should be modified to provide correct information.

**Comment by kynx** [comment]
Have you tried emailing sdk-support@rackspace.com? Putting pressure on them is probably the best bet, esp if you're a paying customer.

**Comment by sneakyimp** [comment]
I have. No response. Makes it really hard to justify building one's business on rackspace technology if they are letting their PHP SDK just wither and die.

**Comment by sneakyimp** [comment]
I spoke to someone at Rackspace each day for the past 3 days. I was told that development work on V2 was "on hold indefinitely." For all intents and purposes, this project is DEAD. USE AT YOUR OWN RISK.

**Comment by kynx** [comment]
If you're looking to transition away, I'd recommend an abstraction layer so changing providers isn't such a hassle. I use:

https://github.com/thephpleague/flysystem
https://github.com/bernardphp/bernard

**Comment by jamiehannaford** [comment]
@sneakyimp I'll try to provide more context, but I assume a lot of this has already been shared with you. Our SDK team went through some changes a year or so back, and a few of the developers moved to other projects (myself included). This is why the v2 Rackspace provider was put on hiatus (the in-progress work is still in the v2 branch). Beforehand I had managed to finish the OpenStack v2 driver.  

For all intents and purposes this SDK still functions for Rackspace public cloud APIs. If you have a RPC installation you can use the OpenStack one instead. For that reason I wouldn't characterize this project as "dead"; I'd say it's in a sustained engineering mode where, at least for the moment, no new features will be added. I've removed the text from the README which led to the initial misunderstanding. 

I definitely empathise with your position, and I truly apologise for the inconvenience, but there's not much more I can say apart from the fact that this SDK currently works, was in the process of being refactored, but that work is no longer underway.

 If you have SDK issues, please contact sdk-support@rackspace.com or open a support ticket, where a Racker from the relevant team will help you.
