### ISSUE TITLE
[curl] 60: SSL certificate problem: unable to get local issuer certificate [ur

### ISSUE THREAD

**Issue by EricGSX** [rackspace/php-opencloud#738]
[curl] 60: SSL certificate problem: unable to get local issuer certificate [url] https://identity.api.rackspacecloud.com/v2.0/tokens

**Comment by cyberkishor** [comment]
Same for me, In my local working fine without any error but in the server it returns the same error 

@EricGSX post solution if you find

**Comment by cyberkishor** [comment]
@EricGSXI found the solution 

if you replace vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem file with https://curl.haxx.se/ca/cacert.pem file your problem will solve i think.

**Comment by EricGSX** [comment]
> @EricGSXI found the solution
> 
> if you replace vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem file with https://curl.haxx.se/ca/cacert.pem file your problem will solve i think.

Thank you very much. I have solved this problem in this way
